const K='gravesmoke.repo.v080dev1';
const app=document.getElementById('app');
const nav=document.getElementById('nav');

function escapeHtml(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function showRuntimeError(error,context='runtime'){let msg=escapeHtml(error?.message||String(error));let stack=escapeHtml(error?.stack||'');let ctx=escapeHtml(context);app.innerHTML=`<div class="panel runtimeError"><h2>Runtime Error</h2><div class="mut">Context: ${ctx}</div><pre class="errorStack">${msg}\n\n${stack}</pre><button class="btn" onclick="location.reload()"><span>Reload</span></button><button class="btn bad" onclick="localStorage.clear();location.reload()"><span>Reset Save</span></button></div>`;nav.hidden=true} window.showRuntimeError=showRuntimeError;
window.addEventListener('error',e=>{let err=e.error||e.message||'Unknown error';showRuntimeError(err,'unhandled')});
window.addEventListener('unhandledrejection',e=>{showRuntimeError(e.reason,'unhandled rejection')});

let D,V,UI,O,P,T,H;
try {
  D=await fetch('./data/game_data.json').then(r=>r.json());
  V=await fetch('./data/greyhook_v08.json').then(r=>r.json());
  UI=await fetch('./data/ui_assets.json').then(r=>r.json());
  O=await fetch('./data/origins.json').then(r=>r.json()).catch(()=>null);
  P=await fetch('./data/progression.json').then(r=>r.json()).catch(()=>null);
  T=await fetch('./data/travel.json').then(r=>r.json()).catch(()=>null);
  H=await fetch('./data/settlements.json').then(r=>r.json()).catch(()=>null);
  D.version=V.version;
} catch(e) {
  showRuntimeError(e,'boot');
}

const baseLeads={market_papers:'rumored',rookery_drain:'rumored',free_writ:'rumored',synod_rites:'rumored',refugee_witness:'rumored'};
const blank=()=>({
  saveVersion:2,
  screen:'origin',node:'gate',log:[],party:[],pool:Object.keys(D.companions),
  name:'',origin:null,backgroundTitle:'',xp:0,level:1,perkPoints:0,perks:[],traits:[],
  stats:{body:5,wits:5,guile:5,presence:5,resolve:5},
  res:{coin:14,food:5,medicine:2,tools:2,heat:0,day:1},
  fac:{iron:0,rook:0,synod:0,free:0,hearth:0,veil:0,red:0},
  crimes:[],leads:{...baseLeads},solutions:[],items:[],clues:['The sealed ledger exists.'],flags:{},
  contract:false,ledger:false,greyhook:false,greyhookInside:false,greyhookRoute:null,greyhookAlert:0,
  prisonerContact:false,prisonerChoice:null,prisonerOutcome:null,morale:0,reactions:[],aftermath:null,
  enemyType:'wanted',enemyPressure:0,routeHistory:[],consequenceLog:[],
  wounds:0,fatigue:0,settlement:null,district:null,settlementVisited:[],roadEventsSeen:[],
  companionState:{}
});
function hydrate(raw){let b=blank(),s={...b,...raw};s.stats={...b.stats,...(raw?.stats||{})};s.res={...b.res,...(raw?.res||{})};s.fac={...b.fac,...(raw?.fac||{})};s.leads={...b.leads,...(raw?.leads||{})};s.flags={...b.flags,...(raw?.flags||{})};if(raw?.companionState)s.companionState={...raw.companionState};for(const k of ['log','party','pool','crimes','solutions','items','clues','reactions','routeHistory','consequenceLog','perks','traits','settlementVisited','roadEventsSeen'])s[k]=Array.isArray(s[k])?s[k]:b[k];return s}
let S=hydrate(JSON.parse(localStorage.getItem(K)||'{}'));
const save=()=>localStorage.setItem(K,JSON.stringify(S));
const hasStoredSave=()=>!!localStorage.getItem(K);
const n=id=>D.nodes[id]||{name:id,desc:'Missing node.',exits:[]};
const lead=id=>D.leads[id];
const item=id=>D.items[id]||{name:id,type:'unknown',tags:[],text:'Missing item data.'};
const comp=id=>D.companions[id]||{name:id,role:'Unknown',tags:[],ability:'Unknown',effect:'Missing companion data.',text:''};
const origin=id=>O?.origins?.[id]||null;
const perk=id=>P?.perks?.[id]||null;
const tmeta=id=>T?.nodeMeta?.[id]||{danger:1,restSafety:'low',forageValue:1};
const settle=id=>H?.settlements?.[id]||null;
const act=a=>String(a).replaceAll('"','&quot;');
const btn=(t,a,c='')=>`<button class="btn ${c}" onclick="${act(a)}">${actionIcon(t,c)}<span>${t}</span></button>`;
const tag=(t,c='')=>`<span class="tag ${c}">${t}</span>`;
const card=(title,body,actions='')=>`<div class="card"><div class="ct">${title}</div><div class="cx">${body}</div>${actions}</div>`;
const assetUrl=src=>src?`./${src}`:'';
function assetImg(asset,cls,alt){if(!asset?.src)return '';let text=alt===undefined?(asset.alt||''):alt;return `<img class="${cls}" src="${assetUrl(asset.src)}" alt="${act(text)}" loading="lazy">`}
function iconEntry(name){return UI.actions?.[name]||UI.nav?.[name]||UI.itemTypes?.[name]||UI.factions?.[name]||(name?{src:`assets/ui/icons/${name}.png`,alt:name}:null)}
function nodeArt(id=S.node){return UI.nodes?.[id]||null} window.nodeArt=nodeArt;
function companionPortrait(id){return UI.companions?.[id]||null} window.companionPortrait=companionPortrait;
function itemIcon(value){let data=typeof value=='string'?item(value):value||{};let tagIcon=(data.tags||[]).map(t=>UI.itemTags?.[t]).find(Boolean);return iconEntry(tagIcon)||UI.itemTypes?.[data.type]||UI.itemTypes?.unknown||null} window.itemIcon=itemIcon;
function factionMark(id){return UI.factions?.[id]||null} window.factionMark=factionMark;
function actionKind(text,cls=''){let t=String(text).toLowerCase();if(cls.includes('bad')||/danger|forced|lockdown|enemy|reset|capture|silence/.test(t))return 'danger';if(/travel|go to|route|reach|road|current node/.test(t))return 'travel';if(/investigate|search|scout|study|gather|lead/.test(t))return 'investigate';if(/speak|ask|question|contact|debrief|rumor/.test(t))return 'speak';if(/camp|rest|forage|save|import|export/.test(t))return 'camp';if(/accept|resolve|choose|recover|take|begin|continue|start|jump|enter/.test(t))return 'resolve';return 'action'}
function actionIcon(text,cls=''){return assetImg(iconEntry(actionKind(text,cls)),'btnIcon','')}
function navIcon(id){return assetImg(UI.nav?.[id],'navIcon','')}
function itemIconHtml(value,cls='itemIcon'){return assetImg(itemIcon(value),cls,'')}
function factionMarkHtml(id,cls='factionMark'){return assetImg(factionMark(id),cls,'')}
function portraitImg(id,cls='portrait'){let c=comp(id),p=companionPortrait(id);return p?assetImg(p,cls,p.alt||c.name):`<div class="${cls} portraitFallback">${(c.name||'?').slice(0,1)}</div>`}
function scenePanel(id=S.node){let art=nodeArt(id);if(!art)return '';return `<figure class="sceneArt"><img src="${assetUrl(art.src)}" alt="${act(art.alt||n(id).name)}" loading="eager"><figcaption>${n(id).name}</figcaption></figure>`}
const any=(need=[],got=[])=>!need?.length||need.some(x=>got.includes(x));
const partyHasTag=t=>S.party.some(id=>(comp(id).tags||[]).includes(t));

function log(t){S.log.unshift(t);S.log=S.log.slice(0,50)}
function addClue(t){if(t&&!S.clues.includes(t))S.clues.push(t)}
function addItem(id){if(id&&!S.items.includes(id))S.items.push(id)}
function addSol(id){if(id&&!S.solutions.includes(id))S.solutions.push(id)}
function setFlag(k,v=true){S.flags[k]=v}
function hasFlag(k){return !!S.flags[k]}
function deltaFac(d={}){for(const k of Object.keys(d))S.fac[k]=(S.fac[k]||0)+d[k]}
function addConsequence(t){if(t&&!S.consequenceLog.includes(t))S.consequenceLog.unshift(t)}
function go(x){S.screen=x;render()} window.go=go;
function reset(){S=blank();localStorage.removeItem(K);go('origin')} window.reset=reset;
function continueGame(){let target=S.screen&&!['title','origin','party'].includes(S.screen)?S.screen:'map';if(S.party.length<3&&!S.contract&&!S.greyhook)target='party';go(target)} window.continueGame=continueGame;
function devGreyhook(){S=blank();S.screen='board';S.party=['mara','nell','ilyra'];S.origin='free_spear_bastard';S.name='Test Spear';S.backgroundTitle='Unproven Spear';S.stats={body:7,wits:5,guile:5,presence:6,resolve:5};S.enemyType='wanted';S.fac.free=5;S.fac.synod=-3;S.items.push('free_spear_token');unlockGreyhook('Dev state: Greyhook vertical slice seeded.');S.node='greyhook_gate';['greyhook_supply_route','quartermaster_blackmail_route','infirmary_route','transfer_forgery_route','greyhook_escape'].forEach(addSol);['greyhook_supply_contract','quartermaster_blackmail','greyhook_infirmary_seal','prisoner_transfer_forgery','greyhook_escape_mark'].forEach(addItem);go('board')} window.devGreyhook=devGreyhook;
function devLowLevel(){S=blank();S.party=['mara','nell','sarn'];S.origin='ledger_thief';S.name='LowTest';S.backgroundTitle='Stolen Page';S.stats={body:5,wits:6,guile:7,presence:5,resolve:5};S.enemyType='wanted';S.fac.rook=5;S.fac.red=3;S.items.push('stolen_ledger_scrap');S.screen='board';go('board')} window.devLowLevel=devLowLevel;

function originScreen(){let list=Object.entries(O.origins||{}).map(([id,o])=>{let statLine=Object.entries(o.stats||{}).map(([k,v])=>`${k}+${v}`).join(', ');let itemName=o.item?item(o.item).name:'';return `<div class="choice ${S.origin==id?'sel':''}" onclick="pickOrigin('${id}')"><div class="ct">${o.name}</div><div class="cx">${o.flavor}<br><b>${o.backgroundTitle}:</b> ${o.desc}<br><b>Stats:</b> ${statLine}<br><b>Item:</b> ${itemName||'none'}<br>${o.checkBonus}<br><i>${o.drawback}</i></div></div>`}).join('');app.innerHTML=header()+`<div class="panel"><h2>Who Are You?</h2><p class="mut">Your origin shapes your stats, starting item, faction ties, and enemy.</p><div class="partyGrid">${list}</div>${S.origin?`<div class="card"><div class="ct">Name</div><div class="cx">${btn('Random','randomName()')}<br><input class="nameInput" id="nameField" value="${act(S.name||'')}" oninput="setName(this.value)"></div></div>${btn(`Begin as ${O.origins[S.origin].name}`,'confirmOrigin()','pri')}`:''}</div>`}
function pickOrigin(id){for(const[k,v]of Object.entries(O.origins[id].stats||{}))S.stats[k]=(S.stats[k]||5)+v;for(const[k,v]of Object.entries(O.origins[id].factionDelta||{}))S.fac[k]=(S.fac[k]||0)+v;if(O.origins[id].item)addItem(O.origins[id].item);S.origin=id;S.backgroundTitle=O.origins[id].backgroundTitle;S.enemyType=O.origins[id].enemyType;if(!S.name)S.name=O.origins[id].name.split(' ')[0];render()} window.pickOrigin=pickOrigin;
function setName(v){S.name=v} window.setName=setName;
const randomNames=['Orin','Marra','Sedge','Halen','Vaulk','Keth','Drenn','Yara','Toller','Ashvein','Brenn','Calla','Reddik','Sive','Halden'];
function randomName(){S.name=randomNames[Math.floor(Math.random()*randomNames.length)];render()} window.randomName=randomName;
function confirmOrigin(){S.screen='party';S.pool=Object.keys(D.companions);render()} window.confirmOrigin=confirmOrigin;

function greyhookAlertBand(){let a=S.greyhookAlert||0;if(a<=1)return 'routine';if(a<=3)return 'tightened searches';if(a===4)return 'lockdown';return 'forced escape / capture'} window.greyhookAlertBand=greyhookAlertBand;
function greyhookAlertText(){let b=greyhookAlertBand();return b==='routine'?'Routine garrison behavior: normal movement, low-risk conversation, ordinary checks.':b==='tightened searches'?'Tightened searches: forged papers are harder, visible weapons are suspicious, patrol confrontation can appear.':b==='lockdown'?'Lockdown: exits are risky, the escape route matters, and enemies can frame you.':'Forced pressure: escape, submit to capture, fight, burn a favor, or use a companion route.'} window.greyhookAlertText=greyhookAlertText;
function isGreyhookLockdown(){return (S.greyhookAlert||0)>=4} window.isGreyhookLockdown=isGreyhookLockdown;
function raiseGreyhookAlert(amount,reason){S.greyhookAlert=Math.max(0,(S.greyhookAlert||0)+amount);if(reason)addClue(`Greyhook alert ${amount>=0?'+':''}${amount}: ${reason}`);if(S.greyhookAlert>=4){S.leads.greyhook_escape_route=S.leads.greyhook_escape_route||'rumored';addClue('Lockdown reveals a Greyhook escape-route lead.');maybeEnemyEscalation('lockdown',false)}log(`Greyhook alert is now ${S.greyhookAlert}/5 — ${greyhookAlertBand()}.`)} window.raiseGreyhookAlert=raiseGreyhookAlert;
const raiseAlert=raiseGreyhookAlert;
function canUseExitFrom(from,nodeId){if(!S.greyhookInside)return true;if(!isGreyhookLockdown())return true;if(S.solutions.includes('greyhook_escape')||S.party.includes('mara')||S.party.includes('nell'))return true;if(['lower_cells','sealed_prisoner_cell'].includes(from))return ['lower_cells','sealed_prisoner_cell'].includes(nodeId);return ['greyhook_outer_yard','lower_cells','sealed_prisoner_cell'].includes(nodeId)}
function canUseExit(nodeId){return canUseExitFrom(S.node,nodeId)} window.canUseExit=canUseExit;

function maybeEnemyEscalation(trigger,renderAfter=true){let e=V.enemyInterference?.[S.enemyType];if(!e||!e.triggers?.includes(trigger))return;S.enemyPressure++;raiseGreyhookAlert(1,e.effect);addClue(`${e.name} interference: ${e.effect}`);addConsequence(`${e.name}: ${e.effect}`);log(`${e.name} interferes at Greyhook.`);if(renderAfter)render()} window.maybeEnemyEscalation=maybeEnemyEscalation;
function enemyInterferenceScene(){maybeEnemyEscalation(S.greyhookRoute||'lockdown')} window.enemyInterferenceScene=enemyInterferenceScene;
function companionReaction(choice){let map=V.companionReactions?.[choice]||{};for(const id of S.party){let text=map[id];if(text&&!S.reactions.includes(text)){S.reactions.push(text);addClue('Companion reaction: '+text);addConsequence(`${comp(id).name}: ${text}`)}}} window.companionReaction=companionReaction;

function header(){return `<div class="head"><h1>Gravesmoke Road</h1><div class="mut">v${D.version} • Day ${S.res.day} • ${n(S.node).name}<br>${tag('food '+S.res.food)}${tag('heat '+S.res.heat)}${S.greyhook?tag('Greyhook '+S.greyhookAlert+'/5: '+greyhookAlertBand(),'red'):''}${S.morale?tag('morale '+S.morale,'green'):''}</div></div>`}
function render(){save();nav.hidden=['title','party'].includes(S.screen);if(!nav.hidden)nav.innerHTML=`<div class="navInner">${['map','board','company','pack','camp'].map(x=>`<button class="${S.screen==x?'active':''}" onclick="go('${x}')">${x}</button>`).join('')}</div>`;({title,map,board,company,pack,camp,party,node:nodeScreen}[S.screen]||map)()} window.render=render;

function title(){app.innerHTML=header()+`<div class="panel"><h2>v0.8.0-dev1 — Greyhook Complete Flow Pass</h2><p>The first full Greyhook flow pass: route families, alert ladder, interior scenes, prisoner fate, companion reactions, aftermath, and next chapter hook.</p>${btn('New Game','reset()','pri')}${btn('Continue','go("map")','good')}${btn('Jump to Greyhook test state','devGreyhook()')}</div>`}
function party(){app.innerHTML=header()+`<div class="panel"><h2>Choose three companions</h2><p class="mut">Companions now actively open Greyhook route fantasies and react to prisoner fate.</p>${S.pool.map(id=>{let c=comp(id);return `<div class="choice ${S.party.includes(id)?'sel':''}" onclick="pickComp('${id}')"><div class="ct">${c.name} — ${c.role}</div><div class="cx">${c.text}<br><b>${c.ability}:</b> ${c.effect}<br>${(c.tags||[]).map(x=>tag(x)).join('')}</div></div>`}).join('')}${S.party.length==3?btn('Begin at Gallowsford Gate','go("map")','pri'):''}</div>`}
function pickComp(id){S.party=S.party.includes(id)?S.party.filter(x=>x!=id):(S.party.length<3?[...S.party,id]:S.party);render()} window.pickComp=pickComp;

const pos={gate:[220,28],market:[305,105],inn:[390,170],chapel:[210,150],ditch:[80,130],road:[145,230],tower:[260,280],mill:[70,285],ford:[350,280],shrine:[185,265],grey_road:[245,335],muster_field:[105,330],quartermaster_tent:[90,235],greyhook_gate:[375,330],greyhook_outer_yard:[300,250],fortress_infirmary:[430,235],synod_archive:[420,140],lower_cells:[305,160],sealed_prisoner_cell:[305,80]};
const roads=[['gate','market'],['gate','ditch'],['gate','road'],['market','inn'],['market','chapel'],['chapel','shrine'],['ditch','road'],['ditch','shrine'],['road','tower'],['road','mill'],['mill','ford'],['inn','ford'],['road','grey_road'],['grey_road','muster_field'],['muster_field','quartermaster_tent'],['quartermaster_tent','greyhook_gate'],['grey_road','greyhook_gate'],['greyhook_gate','greyhook_outer_yard'],['greyhook_outer_yard','fortress_infirmary'],['greyhook_outer_yard','lower_cells'],['lower_cells','sealed_prisoner_cell'],['fortress_infirmary','synod_archive']];
function map(){let exits=n(S.node).exits;let line=(a,b)=>{let A=pos[a],B=pos[b],x=A[0]+42,y=A[1]+23,dx=B[0]-A[0],dy=B[1]-A[1],l=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;return `<div class="road" style="left:${x}px;top:${y}px;width:${l}px;transform:rotate(${ang}deg)"></div>`};let nodes=Object.keys(D.nodes).map(id=>`<div class="node ${id==S.node?'cur':exits.includes(id)?'avail':''} ${hasLeadAt(id)?'leadnode':''}" style="left:${pos[id][0]}px;top:${pos[id][1]}px" onclick="${id==S.node?'go(\'node\')':exits.includes(id)?`travel(\'${id}\')`:''}">${n(id).name}</div>`).join('');app.innerHTML=header()+`<div class="panel"><h2>Map</h2><div class="map">${roads.map(r=>line(r[0],r[1])).join('')}${nodes}</div>${btn('Current node','go("node")','pri')}${btn('Case Board','go("board")','good')}</div><div class="panel"><h2>Road Log</h2><div class="log">${S.log.map(x=>'• '+x+'<br>').join('')}</div></div>`}
function travel(id){if(!canUseExit(id)){raiseGreyhookAlert(1,'attempted movement during lockdown');log('Lockdown blocks the clean exit. Use escape, capture, patrol, or a companion route.');go('board');return}S.node=id;S.res.food=Math.max(0,S.res.food-1);log('Travelled to '+n(id).name+'.');if(id=='grey_road'&&S.greyhook)addClue('Greyhook Road: choose a route card before trusting the gate.');go('node')} window.travel=travel;
function hasLeadAt(id){return Object.entries(D.leads).some(([k,l])=>l.node==id&&S.leads[k]&&!['viable','used'].includes(S.leads[k]))}

function nodeText(){let t=n(S.node).desc;if(S.greyhook&&isGreyhookNode(S.node))t+=' '+greyhookAlertText();return t}
function isGreyhookNode(id){return ['grey_road','muster_field','quartermaster_tent','greyhook_gate','greyhook_outer_yard','fortress_infirmary','lower_cells','sealed_prisoner_cell','synod_archive'].includes(id)}
function nodeScreen(){app.innerHTML=header()+`<div class="panel"><h2>${n(S.node).name}</h2><p>${nodeText()}</p>${nodeActions()}<h3>Roads</h3>${n(S.node).exits.map(id=>btn('Travel to '+n(id).name,`travel('${id}')`,canUseExit(id)?'':'bad')).join('')}</div>`}
function nodeActions(){let s='';let ls=Object.entries(D.leads).filter(([k,l])=>l.node==S.node&&S.leads[k]&&!['viable','used'].includes(S.leads[k]));if(ls.length)s+=ls.map(([k,l])=>btn('Investigate: '+l.name,`investigate('${k}')`,'good')).join('');if(S.node=='tower'&&S.contract&&!S.ledger)s+=btn('Take the ledger by force or parley','ledgerWin()','pri');if(S.node=='greyhook_gate')s+=greyhookApproaches()+sceneButtonsForNode('greyhook_gate');if(S.node=='greyhook_outer_yard')s+=sceneButtonsForNode('greyhook_outer_yard')+btn('Ask companion for Greyhook angle','companionAngle()','good')+btn('Starting enemy interference','enemyInterferenceScene()','bad');if(['quartermaster_tent','fortress_infirmary','lower_cells','synod_archive'].includes(S.node))s+=sceneButtonsForNode(S.node);if(S.node=='sealed_prisoner_cell')s+=sceneButtonsForNode('sealed_prisoner_cell')+prisonerButtons();if(isGreyhookLockdown())s+=btn('Forced escape / capture pressure','escapeOrCapture()','bad');return s||btn('Gather rumor','rumor()')}
function sceneButtonsForNode(nodeId){return Object.entries(V.scenes||{}).filter(([,sc])=>sc.node==nodeId).map(([id,sc])=>btn(sc.label||id,`scene('${id}')`,sceneAvailable(sc)?'good':'bad')).join('')}
function sceneAvailable(sc){let capturedBypass=S.greyhookRoute=='captured'&&S.node=='lower_cells';return capturedBypass||(any(sc.requiresAnySolution||[],S.solutions)&&any(sc.requiresAnyItem||[],S.items))}
function prisonerButtons(){return btn('Speak to sealed prisoner','prisonerContact()','pri')+['question','extract','silence','trade'].map(c=>btn(`${V.prisonerChoices[c].label} prisoner`,`prisonerChoice('${c}')`,c=='question'?'good':c=='extract'?'pri':'bad')).join('')}

function board(){let ledgerRoutes=routeCards('sealed_ledger'),greyRoutes=routeCards('greyhook_fortress');app.innerHTML=header()+`<div class="panel"><h2>Case Board</h2>${section('Objective',objectiveCard()+nextCard())}${section('Routes',ledgerRoutes+greyRoutes)}${section('Interior Status',interiorStatus())}${section('Prisoner Fate',prisonerFateCard())}${section('Alert',alertCard())}${section('Companion Reactions',reactionCards())}${section('Consequences',consequenceCards())}${section('Next Step',nextStep())}${section('Clues',S.clues.map(c=>card('Clue',c)).join(''))}</div>`}
function section(t,html){return `<h3>${t}</h3>${html||card('None','No entries yet.')}`}
function objectiveCard(){let title=S.greyhook?V.chapters.greyhook_fortress.title:V.chapters.sealed_ledger.title;let obj=currentObjective();let actions=!S.contract&&!S.greyhook?btn('Accept The Sealed Ledger','acceptLedger()','pri'):S.ledger?resolutionButtons():S.prisonerOutcome&&!S.aftermath&&!hasFlag('extraction_pressure')?btn('Resolve Greyhook chapter','resolveGreyhook()','pri'):'';return card(title,obj,actions)}
function currentObjective(){if(!S.contract&&!S.greyhook)return 'Start a new investigation: accept The Sealed Ledger.';if(S.ledger)return 'The ledger is recovered. Choose which faction receives it to open Greyhook.';if(S.contract&&!S.ledger)return 'Recover the Ledger at the Old Watchtower. Investigate at least one route if the way feels blocked.';if(S.greyhook&&!S.greyhookInside)return 'Reach Greyhook Fortress and commit to an entry route.';if(S.greyhookInside&&!S.prisonerContact)return 'Reach the sealed prisoner through Greyhook interior pressure.';if(S.prisonerContact&&!S.prisonerOutcome)return 'Decide prisoner fate: question, extract, silence, or trade.';if(hasFlag('extraction_pressure'))return 'Extraction has started. Escape, submit to capture, or use the escape route.';return 'Greyhook has an outcome. Resolve the chapter and carry the consequence forward.'}
function nextCard(){return card('Recommended next',recommendedNext())}
function recommendedNext(){if(!S.contract&&!S.greyhook)return 'Accept The Sealed Ledger from the Case Board.';if(S.contract&&!S.ledger){let l=Object.entries(D.leads).find(([k,x])=>x.chapter=='sealed_ledger'&&S.leads[k]=='rumored');return l?`Investigate ${l[1].name} at ${n(l[1].node).name}.`:'Go to Old Watchtower and recover the ledger.'}if(S.greyhook&&!S.greyhookInside){let l=Object.entries(D.leads).find(([k,x])=>x.chapter=='greyhook_fortress'&&S.leads[k]=='rumored');return l?`Investigate ${l[1].name} at ${n(l[1].node).name}.`:'Commit to a viable route at Greyhook Gate.'}if(S.greyhookInside&&!S.prisonerContact)return S.node=='lower_cells'?'Attempt lower-cell access or use captured-inside pressure.':'Reach Lower Cells from the Greyhook Outer Yard.';if(S.prisonerContact&&!S.prisonerOutcome)return 'Choose the prisoner fate. Risks are visible below.';if(hasFlag('extraction_pressure'))return 'Use the escape route if prepared; otherwise capture becomes the failed-forward route.';return `Next story hook: ${V.chapters.greyhook_fortress.nextHook}.`}
function routeCards(chapter){return Object.entries(D.leads).filter(([,l])=>l.chapter==chapter).map(([k,l])=>{let state=S.leads[k]||'unknown',body=`${l.text}<br><b>Where:</b> ${n(l.node).name} • <b>Check:</b> ${l.stat.toUpperCase()} ${l.dc}<br><b>Reward:</b> ${l.item?item(l.item).name:'none'}<br><b>State:</b> ${state}${l.transformsTo?'<br><b>Failed-forward:</b> '+l.transformsTo.map(x=>D.leads[x]?.name||x).join(', '):''}`;return card(l.name,body,state!='unknown'?btn('Travel / investigate',`routeTo('${l.node}')`,'good'):'')}).join('')}
function interiorStatus(){if(!S.greyhook)return card('Greyhook unopened','Resolve the Ledger to reveal Greyhook routes.');return card('Greyhook Interior',`Route used: ${S.greyhookRoute||'none'}<br>Inside: ${S.greyhookInside?'yes':'no'}<br>Current node: ${n(S.node).name}<br>Lower-cell access: ${S.items.includes('lower_cell_ring_key')||S.items.includes('greyhook_infirmary_seal')||S.items.includes('prisoner_transfer_forgery')||S.greyhookRoute=='captured'?'available':'blocked'}<br>Escape route: ${S.solutions.includes('greyhook_escape')?'prepared':'unprepared'}`)}
function prisonerFateCard(){let risks='Question: safest truth path.<br>Extract: raises alert and demands escape/capture resolution.<br>Silence: crime, morale damage, Red Ledger value.<br>Trade: reward, betrayal receipt, companion trust damage.';return card('Prisoner Fate',`Contact: ${S.prisonerContact?'yes':'no'}<br>Choice: ${S.prisonerChoice||'none'}<br>Outcome: ${S.prisonerOutcome||'unresolved'}<br>${risks}`)}
function alertCard(){return card(`Alert ${S.greyhookAlert}/5 — ${greyhookAlertBand()}`,greyhookAlertText()+`<br>Lockdown: ${isGreyhookLockdown()?'yes':'no'}<br>Enemy pressure: ${S.enemyPressure||0}`)}
function reactionCards(){return S.reactions.map(r=>card('Reaction',r)).join('')}
function consequenceCards(){let f=Object.entries(S.fac).filter(([,v])=>v).map(([k,v])=>`${D.factions[k].name}: ${v>0?'+':''}${v}`).join('<br>')||'No faction shifts yet.';let c=S.crimes.length?S.crimes.map(x=>tag(x,'red')).join(''):'No recorded crimes.';let extra=S.consequenceLog.map(x=>card('Consequence',x)).join('');return card('Faction Changes',f)+card('Legal / Crime Record',c)+card('Party Morale',String(S.morale||0))+extra}
function nextStep(){let txt=recommendedNext();let action='';if(S.contract&&!S.ledger&&S.solutions.length)action=btn('Go to Old Watchtower','routeTo("tower")','good');if(S.greyhook&&!S.greyhookInside)action+=btn('Go to Greyhook Gate','routeTo("greyhook_gate")','good');if(hasFlag('extraction_pressure'))action+=btn('Face escape / capture pressure','escapeOrCapture()','bad');if(S.prisonerOutcome&&!S.aftermath&&!hasFlag('extraction_pressure'))action+=btn('Resolve Greyhook chapter','resolveGreyhook()','pri');return card('Next',txt,action)}
function routeTo(id){if(id==S.node)go('node');else if(n(S.node).exits.includes(id))travel(id);else{log('Route target: '+n(id).name+'. Use connected map roads to reach it.');go('map')}} window.routeTo=routeTo;

function acceptLedger(){S.contract=true;log('Accepted The Sealed Ledger.');go('board')} window.acceptLedger=acceptLedger;
function checkScore(L){let score=S.stats[L.stat]||0;if(L.chapter=='greyhook_fortress')score+=routeBonus(L);return score}
function routeBonus(L){let bonus=0;if(L.solution=='greyhook_supply_route'&&(S.fac.free>=5||S.party.includes('hadrik')||partyHasTag('martial')))bonus+=2;if(L.solution=='quartermaster_blackmail_route'&&(S.fac.red>=5||S.party.includes('sarn')||S.party.includes('nell')||partyHasTag('criminal')))bonus+=2;if(L.solution=='infirmary_route'&&(S.fac.synod>=5||S.party.includes('ilyra')||S.party.includes('cael')||partyHasTag('healer')))bonus+=2;if(L.solution=='transfer_forgery_route'&&(S.items.includes('forged_papers')||S.party.includes('nell')||S.party.includes('sarn')))bonus+=2;if(L.solution=='greyhook_escape'&&(S.party.includes('mara')||S.party.includes('nell')||partyHasTag('scout')))bonus+=2;return bonus}
function investigate(k){let L=lead(k);if(!L)return;let ok=checkScore(L)>=L.dc-1;if(ok){S.leads[k]='viable';addSol(L.solution);addItem(L.item);addClue('Viable route: '+L.name);awardXp(3,'investigate_lead');if(L.chapter=='greyhook_fortress'){addClue(`Greyhook route card viable: ${L.name}.`);awardXp(2,'route_viable')}log(`${L.name} becomes viable.`)}else{S.leads[k]='failed_forward';addClue('Failed forward: '+L.name+' — '+L.softFail);(L.transformsTo||[]).forEach(t=>S.leads[t]='rumored');if(k=='greyhook_transfer'){addSol('captured_inside_route');addClue('Failed forgery opens captured-inside route.');return enterGreyhook('captured')}log(`${L.name} failed forward and opened another lead.`)}render()} window.investigate=investigate;
function rumor(){let k=Object.keys(D.leads).find(x=>!S.leads[x]);if(k){S.leads[k]='rumored';log('Rumor gained: '+lead(k).name)}else log('No fresh rumor.');render()} window.rumor=rumor;
function ledgerWin(){S.ledger=true;addClue('Recovered the sealed ledger.');awardXp(5,'ledger_resolved');log('The ledger is yours. Choose who benefits, then Greyhook opens.');go('board')} window.ledgerWin=ledgerWin;
function resolutionButtons(){return ['iron','rook','synod','hearth','red'].map(f=>btn('Resolve with '+D.factions[f].name,`finishLedger('${f}')`)).join('')}
function unlockGreyhook(reason='Greyhook Fortress holds a sealed prisoner.'){S.greyhook=true;['greyhook_supply','greyhook_quartermaster','greyhook_infirmary','greyhook_transfer','greyhook_escape_route'].forEach(k=>S.leads[k]=S.leads[k]||'rumored');addClue('Greyhook Fortress holds a sealed prisoner.');addClue('Greyhook route cards are now active on the Case Board.');setFlag('greyhook_unlocked');log(reason)}
function finishLedger(f){S.fac[f]+=10;S.contract=false;S.ledger=false;unlockGreyhook('Ledger resolved. Greyhook chapter opens.');go('board')} window.finishLedger=finishLedger;

function greyhookApproaches(){let out='';for(const [id,a] of Object.entries(V.approaches.greyhook||{})){if(id=='escape')continue;let ok=!a.requiresAnySolution?.length||a.requiresAnySolution.some(x=>S.solutions.includes(x));if(ok)out+=btn(a.label,`enterGreyhook('${id}')`,id=='captured'?'bad':'pri')}if(!out)out=card('No clean entry yet','Investigate Greyhook route cards or deliberately use captured-inside route.',btn('Submit to captured-inside route','enterGreyhook("captured")','bad'));return out}
function enterGreyhook(kind){let a=V.approaches.greyhook[kind];S.greyhook=true;S.greyhookInside=true;S.greyhookRoute=kind;S.routeHistory.push(kind);S.node=a.entryNode;raiseGreyhookAlert(a.alert||0,a.label);awardXp(5,'enter_greyhook');if(kind=='captured'){addSol('captured_inside_route');setFlag('captured_inside');S.morale-=1;S.crimes.push('detained inside Greyhook');addConsequence('Captured-inside route: wound, morale damage, temporary item loss or heat implied.')}if(kind=='forgery')maybeEnemyEscalation('forgery',false);if(kind=='blackmail')maybeEnemyEscalation('blackmail',false);if(kind=='infirmary')maybeEnemyEscalation('infirmary',false);addClue('Greyhook entered: '+a.label+'. '+a.text);log('Entered Greyhook by '+a.label+'.');go('node')} window.enterGreyhook=enterGreyhook;
function scene(id){let sc=V.scenes[id];if(!sc)return;let capturedBypass=S.greyhookRoute=='captured'&&S.node=='lower_cells';if(!capturedBypass&&sc.requiresAnySolution&&!sc.requiresAnySolution.some(x=>S.solutions.includes(x))){raiseGreyhookAlert(1,'scene requirement missing: '+(sc.label||id));log('The scene resists you and alert rises.');render();return}if(!capturedBypass&&sc.requiresAnyItem&&!sc.requiresAnyItem.some(x=>S.items.includes(x))){raiseGreyhookAlert(1,'missing key/paper for '+(sc.label||id));log('You lack the right key, paper, or cover.');render();return}if(sc.solution)addSol(sc.solution);if(sc.item)addItem(sc.item);if(sc.alertChange)raiseGreyhookAlert(sc.alertChange,sc.label||id);if(sc.clue)addClue(sc.clue);if(id==='archive_hook'||id==='archive_seal'||id==='bell_underwater'){awardXp(4,'synod_hook');setFlag('dead_name_index_hook')}if(['lower_cell_access','captured_inside','talk_past_cell_guard','smuggle_message'].includes(id))S.node='sealed_prisoner_cell';if(id=='search_escape_mark')addSol('greyhook_escape');if(id=='enemy_recognition'||id=='starting_enemy_interference')maybeEnemyEscalation(S.greyhookRoute||'high_alert',false);log(sc.clue||('Scene resolved: '+id));render()} window.scene=scene;

function prisonerContact(){if(S.prisonerContact){log('The prisoner has already answered.');render();return}S.prisonerContact=true;awardXp(4,'prisoner_contact');scene('first_contact');maybeEnemyEscalation('prisoner_contact',false);render()} window.prisonerContact=prisonerContact;
function prisonerChoice(c){if(!S.prisonerContact){log('Contact the prisoner first.');render();return}let ch=V.prisonerChoices[c];S.prisonerChoice=c;S.prisonerOutcome=ch.outcome;addItem(ch.item);deltaFac(ch.factionDeltas);S.morale=(S.morale||0)+(ch.morale||0);if(ch.crime&&!S.crimes.includes(ch.crime))S.crimes.push(ch.crime);raiseGreyhookAlert(ch.alert||0,ch.label+' prisoner');companionReaction(c);awardXp(6,'prisoner_fate');updateCompanionState(c);addConsequence(`Prisoner Fate: ${ch.outcome}. ${ch.nextHook}`);addClue('Prisoner fate: '+ch.outcome+'. '+ch.nextHook);if(c=='extract'){setFlag('extraction_pressure');S.leads.greyhook_escape_route=S.leads.greyhook_escape_route||'rumored';maybeEnemyEscalation('extract',false)}if(c=='trade')maybeEnemyEscalation('trade',false);if(c=='question')maybeEnemyEscalation('question',false);log('Prisoner choice: '+ch.label+'.');render()} window.prisonerChoice=prisonerChoice;
function updateCompanionState(choice){if(!S.companionState)S.companionState={};for(const id of S.party)S.companionState[id]=S.companionState[id]||{loyalty:0,stress:0,wound:0};let map={question:{mara:{loyalty:1},ilyra:{loyalty:1},cael:{loyalty:1},brig:{loyalty:-1}},extract:{mara:{loyalty:1},hadrik:{loyalty:1},nell:{loyalty:1}},silence:{ilyra:{loyalty:-2,stress:1},cael:{loyalty:-2},nell:{loyalty:-2},mara:{stress:1},miren:{stress:1},brig:{loyalty:1}},trade:{hadrik:{loyalty:-2},nell:{loyalty:-2},ilyra:{loyalty:-1},mara:{loyalty:-1},sarn:{loyalty:1},brig:{loyalty:1}}};let deltas=map[choice]||{};for(const[id,v]of Object.entries(deltas)){if(S.companionState[id]){if(v.loyalty)S.companionState[id].loyalty+=v.loyalty;if(v.stress)S.companionState[id].stress+=v.stress}}}
function resolveGreyhook(){if(!S.prisonerOutcome){log('Choose prisoner fate first.');return render()}if(hasFlag('extraction_pressure')){log('Extraction must face escape/capture pressure before chapter resolution.');return go('board')}S.aftermath=`Greyhook resolved: ${S.prisonerOutcome}. Next: ${V.chapters.greyhook_fortress.nextHook}`;addClue(S.aftermath);addConsequence(S.aftermath);awardXp(8,'resolve_greyhook');setFlag('greyhook_resolved');S.greyhookInside=false;S.node=S.greyhookAlert>=5?'grey_road':'synod_archive';log(S.aftermath);render()} window.resolveGreyhook=resolveGreyhook;
function companionAngle(){let acted=false;for(const p of S.party){let name=comp(p).name;if(p=='mara'){addSol('greyhook_escape');addItem('greyhook_escape_mark');raiseGreyhookAlert(-1,name+' scouts an exit');acted=true}if(p=='nell'){addSol('greyhook_escape');addSol('transfer_forgery_route');raiseGreyhookAlert(-1,name+' finds a second door');acted=true}if(p=='hadrik'){addSol('greyhook_supply_route');addClue(name+' makes the supply escort look soldierly.');acted=true}if(p=='ilyra'||p=='cael'){addSol('infirmary_route');addClue(name+' gives the infirmary route moral authority.');acted=true}if(p=='sarn'){addSol('quartermaster_blackmail_route');S.leads.greyhook_escape_route='rumored';addClue('Sarn identifies the ink used on lower-cell records.');acted=true}if(p=='brig'){addSol('violent_distraction');raiseGreyhookAlert(1,'Brig creates a violent distraction');acted=true}if(p=='miren'){S.fac.veil+=2;addClue('Miren hears dead names under the lower cells.');acted=true}}if(!acted)log('No companion finds a new Greyhook angle.');else log('Companion Greyhook angles updated.');render()} window.companionAngle=companionAngle;
function patrol(){if(S.stats.presence>=7||S.items.includes('greyhook_search_stamp')||S.greyhookRoute=='infirmary'){raiseGreyhookAlert(-1,'patrol talked down');addClue('Patrol confrontation survived.')}else{raiseGreyhookAlert(1,'patrol confrontation failed');if(!S.crimes.includes('Greyhook patrol beating'))S.crimes.push('Greyhook patrol beating')}render()} window.patrol=patrol;
function escapeMark(){addItem('greyhook_escape_mark');addSol('greyhook_escape');addClue('Escape mark found near the drainage stair.');log('Escape route secured.');render()} window.escapeMark=escapeMark;
function escapeOrCapture(){if(S.solutions.includes('greyhook_escape')||S.party.includes('mara')||S.party.includes('nell')){S.node='grey_road';S.greyhookInside=false;setFlag('extraction_pressure',false);setFlag('extraction_resolved');raiseGreyhookAlert(-2,'forced escape succeeded');addConsequence('Escape/capture status: escaped Greyhook under pressure.');log('Forced escape succeeds.')}else{S.node='lower_cells';S.greyhookInside=true;S.greyhookRoute='captured';setFlag('extraction_pressure',false);setFlag('captured_inside');addSol('captured_inside_route');if(!S.crimes.includes('captured in Greyhook'))S.crimes.push('captured in Greyhook');S.morale-=1;addClue('Escape failed forward into the captured-inside route.');addConsequence('Escape/capture status: captured inside Greyhook, but closer to the cells.');log('Escape fails forward into capture.')}render()} window.escapeOrCapture=escapeOrCapture;

function perkBonus(condition){if(!P?.perks)return 0;let total=0;for(const pk of S.perks){let p=P.perks[pk];if(!p?.implementedEffect||!p.bonus)continue;if(!p.bonus.condition||p.bonus.condition===condition)total+=p.bonus.value||0}return total}
function originCheckBonus(){let o=origin(S.origin);if(!o)return 0;return 1}
function awardXp(amount,reason){if(!amount||!P)return;let key=`_xpgrant_${reason}`;if(S.flags[key])return;setFlag(key);S.xp=(S.xp||0)+amount;log(`+${amount} XP: ${P.xpAwards?.[reason]?.desc||reason}`);checkLevelUp();save()}
function checkLevelUp(){if(!P?.xpThresholds)return;let t=P.xpThresholds,newLevel=S.level||1;while(newLevel<t.length&&S.xp>=t[newLevel])newLevel++;if(newLevel>S.level){S.level=newLevel;S.perkPoints=(S.perkPoints||0)+1;log(`Level ${S.level}! Perk point gained.`);addClue(`Level ${S.level} reached.`)}} window.checkLevelUp=checkLevelUp;
function learnPerk(id){if(!P?.perks[id])return;if(S.perks.includes(id)){log('Perk already learned.');render();return}if(!S.perkPoints||S.perkPoints<=0){log('No perk points available.');render();return}S.perkPoints--;S.perks.push(id);log(`Learned perk: ${P.perks[id].name}.`);addClue(`Perk learned: ${P.perks[id].name}`);render()} window.learnPerk=learnPerk;
checkScore=function(L){let score=(S.stats[L.stat]||0)+perkBonus(L.stat)+perkBonus(L.solution)+originCheckBonus();if(L.chapter=='greyhook_fortress')score+=routeBonus(L);return score};
function perkList(){if(!P?.perks)return'';let learned=S.perks.map(id=>{let p=P.perks[id];return p?card(`${p.name} (Learned)`,`${p.effect}`):''}).filter(Boolean).join('');let header=learned?'<h3>Learned Perks</h3>'+learned:'';if(S.perkPoints>0){let available=Object.entries(P.perks).filter(([id,p])=>!S.perks.includes(id));let items=available.map(([id,p])=>card(p.name,`${p.desc} ${p.effect}`,btn('Learn perk',`learnPerk('${id}')`,'good'))).join('');header+=card(`Perk Points: ${S.perkPoints}`,items||'No perks available to learn.')}return header}
function travelResultCard(steps,path){let m=tmeta(S.node);let cost=`Food: -${steps}  Fatigue: +${steps}${S.fatigue>=3?tag('Winded','purple'):''}`;let info=m.danger>=4?tag('Hostile area','red'):m.danger>=3?tag('Dangerous road','purple'):m.restSafety==='medium'?tag('Safe rest','green'):'';return card('Travel Result',`<b>Arrived:</b> ${n(S.node).name}<br>${cost}<br>${info?info+'<br>':''}Day ${S.res.day} • Fatigue ${S.fatigue}/6 • Food ${S.res.food}`)}
function maybeRoadEvent(){if(!T?.roadEvents?.length)return;let m=tmeta(S.node);if(Math.random()>m.danger/6)return;let pool=T.roadEvents.filter(e=>{let tags=e.triggerTags||[];if(tags.includes('road')||tags.includes('wilderness'))return true;if(tags.includes(m.terrain||'road'))return true;if(tags.includes(m.factionOwner||''))return true;return false});if(!pool.length)return;let ev=pool[Math.floor(Math.random()*pool.length)];if(S.roadEventsSeen.includes(ev.id))return;S.roadEventsSeen.push(ev.id);awardXp(1,'road_event');goRoadEvent(ev)}
function goRoadEvent(ev){let choices=ev.choices.map(c=>{let check=c.cost?Object.entries(c.cost).map(([k,v])=>`${k} ${v}`).join(' '):'';return btn(check?`${c.label} (${check})`:c.label,`resolveRoadEvent('${ev.id}',${ev.choices.indexOf(c)})`)}).join('');app.innerHTML=header()+`<div class="panel roadEventPanel"><h2>${ev.title}</h2><p>${ev.text}</p>${choices}${btn('Skip','render()')}</div>`}
function resolveRoadEvent(evId,idx){let ev=T.roadEvents.find(e=>e.id===evId);if(!ev||!ev.choices[idx]){render();return}let c=ev.choices[idx],ok=true;if(c.cost)for(const[k,v]of Object.entries(c.cost)){if(k==='coin'&&S.res.coin<v)ok=false;if(k==='food'&&S.res.food<v)ok=false;if(k==='medicine'&&S.res.medicine<v)ok=false;if(k==='wits'&&(S.stats.wits||5)<v)ok=false;if(k==='body'&&(S.stats.body||5)<v)ok=false;if(k==='guile'&&(S.stats.guile||5)<v)ok=false;if(k==='presence'&&(S.stats.presence||5)<v)ok=false;if(k==='resolve'&&(S.stats.resolve||5)<v)ok=false}let con=ok?c.consequence:(c.failConsequence||c.consequence);if(c.cost&&ok){if(c.cost.coin)S.res.coin-=c.cost.coin;if(c.cost.food)S.res.food-=c.cost.food;if(c.cost.medicine)S.res.medicine-=c.cost.medicine}if(con){if(con.food)S.res.food=Math.max(0,(S.res.food||0)+con.food);if(con.coin)S.res.coin=Math.max(0,(S.res.coin||0)+con.coin);if(con.heat)S.res.heat=Math.min(6,Math.max(0,(S.res.heat||0)+con.heat));if(con.fatigue)S.fatigue=Math.max(0,(S.fatigue||0)+con.fatigue);if(con.wounds)S.wounds=(S.wounds||0)+con.wounds;if(con.morale)S.morale=(S.morale||0)+con.morale;if(con.medicine)S.res.medicine=Math.max(0,(S.res.medicine||0)+con.medicine);if(con.xp)S.xp=(S.xp||0)+con.xp;if(con.fac)deltaFac(con.fac);if(con.clue)addClue(con.clue);if(con.item)addItem(con.item);if(con.lead)S.leads[con.lead]='rumored';if(con.crime&&!S.crimes.includes(con.crime))S.crimes.push(con.crime);if(con.resolvePenalty)S.stats.resolve=Math.max(1,(S.stats.resolve||5)-con.resolvePenalty)}log(c.consequence?.clue||('Road event: '+ev.title));render()} window.resolveRoadEvent=resolveRoadEvent;
function withinSettlement(){let m=tmeta(S.node);return m.settlementId||null}
function settlementScreen(){let sid=withinSettlement(),s=settle(sid);if(!s){go('node');return}S.settlement=sid;if(!S.settlementVisited.includes(sid))S.settlementVisited.push(sid);let services=s.services.map(sv=>{let cost=sv.cost?` (${sv.cost} coin)`:'';return btn(sv.label+cost,`settlementService('${sv.id}')`,'good')}).join('');let districts=s.districts.map(d=>{let name=n(d).name;return S.node==d?tag(name,'green'):`<span class="tag">${name}</span>`}).join(' ');let legal=tag('Legal '+s.legalPressure,s.legalPressure>=4?'red':'purple');let faction=tag(s.factionOwner||'unclaimed');app.innerHTML=header()+`<div class="panel settlementPanel"><h2>${s.name}</h2><p>${s.desc}</p><div class="mut">${legal} ${faction} ${districts}</div><h3>Services</h3>${services||'<p>No services available here.</p>'}${btn('Leave settlement','go("map")')}</div>`}
function settlementService(sid){if(!H?.settlements)return;let s=null,sv=null;for(const[sid2,st]of Object.entries(H.settlements)){let found=st.services.find(x=>x.id===sid);if(found){s=st;sv=found;break}}if(!sv)return;awardXp(1,'settlement_service');let e=sv.effect;if(e.coin)S.res.coin=Math.max(0,(S.res.coin||0)+(e.coin||0));if(e.food)S.res.food=Math.max(0,(S.res.food||0)+(e.food||0));if(e.medicine)S.res.medicine=Math.max(0,(S.res.medicine||0)+(e.medicine||0));if(e.fatigue)S.fatigue=Math.max(0,(S.fatigue||0)+(e.fatigue||0));if(e.wounds)S.wounds=Math.max(0,(S.wounds||0)+(e.wounds||0));if(e.fac)deltaFac(e.fac);if(e.clue)addClue(e.clue);if(e.item)addItem(e.item);if(e.action==='rumor'){let k=Object.keys(D.leads).find(x=>!S.leads[x]);if(k){S.leads[k]='rumored';log('Rumor gained: '+lead(k).name)}}if(e.action==='seekPapers'){S.leads.free_writ='rumored';addItem('forged_papers');addClue('Acquired travel writs.');log('Papers acquired.')}if(e.action==='rookeryContact'){S.leads.rookery_drain='rumored';addClue('Rookery contact made.');log('Rookery contact made.')}if(e.action==='scene_archive_hook')scene('archive_hook');if(e.action==='infirmaryCover'&&S.solutions.includes('infirmary_route')){raiseGreyhookAlert(-1,'infirmary cover');addClue('Infirmary cover active.');log('Infirmary cover applied.')}if(e.action==='quartermasterDeal'&&S.items.includes('quartermaster_blackmail')){addItem('lower_cell_ring_key');addClue('Quartermaster deal secured.');log('Quartermaster deal complete.')}if(sv.desc)addClue(sv.desc);render()} window.settlementService=settlementService;

function company(){app.innerHTML=header()+`<div class="panel"><h2>Company</h2>${S.party.map(id=>{let c=comp(id);return card(`${c.name} — ${c.role}`,`${c.text}<br><b>${c.ability}:</b> ${c.effect}<br>${(c.tags||[]).map(x=>tag(x)).join('')}`)}).join('')}<h3>Morale</h3>${tag(S.morale||0,S.morale<0?'red':'green')}<h3>Companion Reactions</h3>${reactionCards()||'<p>No major reaction yet.</p>'}<h3>Crimes</h3>${S.crimes.map(c=>tag(c,'red')).join('')||'<p>No recorded crimes.</p>'}</div>`}
function pack(){app.innerHTML=header()+`<div class="panel"><h2>Pack & Papers</h2>${S.items.map(id=>{let i=item(id);return card(`${i.name} — ${i.type}`,`${i.text}<br>${(i.tags||[]).map(x=>tag(x)).join('')}`)}).join('')||'<p>No special items yet.</p>'}</div>`}
function camp(){app.innerHTML=header()+`<div class="panel"><h2>Camp</h2>${btn('Scout a rumor','rumor()')}${btn('Plan Greyhook escape / reduce alert','campEscape()')}${btn('Debrief prisoner choice','campDebrief()')}${btn('Rest and eat','rest()')}</div>`}
function campEscape(){if(S.greyhook){raiseGreyhookAlert(-1,'camp escape planning');S.leads.greyhook_escape_route='rumored';addSol('greyhook_escape');addClue('Camp plan: Greyhook escape route prepared.')}render()} window.campEscape=campEscape;
function campDebrief(){if(S.prisonerChoice){companionReaction(S.prisonerChoice);addItem('companion_objection_note');addClue('Camp debrief: prisoner fate discussed.')}else log('No prisoner choice to debrief yet.');render()} window.campDebrief=campDebrief;
function rest(){S.res.food=Math.max(0,S.res.food-1);S.res.day++;log('Rested.');render()} window.rest=rest;

function resourceRail(){return `<div class="resourceRail">${tag('coin '+S.res.coin,'gold')}${tag('food '+S.res.food,S.res.food<=1?'red':'')}${tag('med '+S.res.medicine)}${tag('tools '+S.res.tools)}${tag('heat '+S.res.heat,S.res.heat>=4?'red':'')}${S.greyhook?tag('Greyhook '+S.greyhookAlert+'/5: '+greyhookAlertBand(),S.greyhookAlert>=4?'red':'purple'):''}${S.morale?tag('morale '+S.morale,S.morale<0?'red':'green'):''}</div>`}
header=function(){return `<div class="head"><div><h1>Gravesmoke Road</h1><div class="mut">v${D.version} â€¢ Day ${S.res.day} â€¢ ${n(S.node).name}</div></div>${resourceRail()}</div>`};
function hasChapterSolution(chapter){return Object.values(D.leads).some(l=>l.chapter==chapter&&S.solutions.includes(l.solution))}
function hasGreyhookEntryRoute(){return Object.entries(V.approaches.greyhook||{}).some(([id,a])=>!['captured','escape'].includes(id)&&(!a.requiresAnySolution?.length||a.requiresAnySolution.some(x=>S.solutions.includes(x))))}
function nextLead(chapter){return Object.entries(D.leads).find(([k,x])=>x.chapter==chapter&&S.leads[k]=='rumored')}
recommendedNext=function(){if(S.party.length<3&&!S.contract&&!S.greyhook)return 'Choose three companions to begin the road.';if(!S.contract&&!S.greyhook)return 'Accept The Sealed Ledger from the Case Board.';if(S.ledger)return 'Resolve the ledger with a faction to unlock Greyhook Fortress.';if(S.contract&&!S.ledger){if(hasChapterSolution('sealed_ledger'))return 'Go to Old Watchtower and recover the ledger.';let l=nextLead('sealed_ledger');return l?`Investigate ${l[1].name} at ${n(l[1].node).name}.`:'Find one viable route, then recover the ledger at Old Watchtower.'}if(S.greyhook&&!S.greyhookInside){if(hasGreyhookEntryRoute())return 'Go to Greyhook Gate and commit to a viable entry route.';let l=nextLead('greyhook_fortress');return l?`Investigate ${l[1].name} at ${n(l[1].node).name}.`:'Use the captured-inside route if no clean route is ready.'}if(S.greyhookInside&&!S.prisonerContact)return S.node=='sealed_prisoner_cell'?'Speak to the sealed prisoner.':S.node=='lower_cells'?'Use a lower-cell scene to reach the sealed prisoner.':'Reach Lower Cells from the Greyhook interior.';if(S.prisonerContact&&!S.prisonerOutcome)return 'Choose the prisoner fate. The Case Board shows the risks.';if(hasFlag('extraction_pressure'))return 'Use the escape route if prepared; otherwise capture becomes the failed-forward route.';if(S.prisonerOutcome&&!S.aftermath)return 'Resolve the Greyhook chapter and carry the consequence forward.';return `Next story hook: ${V.chapters.greyhook_fortress.nextHook}.`};
function guideAction(){if(S.party.length<3&&!S.contract&&!S.greyhook)return{label:'Choose company',action:'go("party")',cls:'pri'};if(!S.contract&&!S.greyhook)return{label:'Accept case',action:'acceptLedger()',cls:'pri'};if(S.ledger)return{label:'Choose faction',action:'go("board")',cls:'pri'};if(S.contract&&!S.ledger){if(hasChapterSolution('sealed_ledger'))return{label:'Recover ledger',action:'routeTo("tower")',cls:'pri'};let leadEntry=nextLead('sealed_ledger');if(leadEntry){let[k,l]=leadEntry;return S.node==l.node?{label:'Investigate lead',action:`investigate('${k}')`,cls:'pri'}:{label:'Travel to lead',action:`routeTo('${l.node}')`,cls:'good'}}return{label:'Open Case Board',action:'go("board")',cls:'good'}}if(S.greyhook&&!S.greyhookInside){if(hasGreyhookEntryRoute())return S.node=='greyhook_gate'?{label:'Choose entry route',action:'go("node")',cls:'pri'}:{label:'Go to Greyhook Gate',action:'routeTo("greyhook_gate")',cls:'good'};let leadEntry=nextLead('greyhook_fortress');if(leadEntry){let[k,l]=leadEntry;return S.node==l.node?{label:'Investigate route',action:`investigate('${k}')`,cls:'pri'}:{label:'Travel to route',action:`routeTo('${l.node}')`,cls:'good'}}return{label:'Use captured route',action:'enterGreyhook("captured")',cls:'bad'}}if(S.greyhookInside&&!S.prisonerContact){if(S.node=='sealed_prisoner_cell')return{label:'Speak to prisoner',action:'prisonerContact()',cls:'pri'};if(S.node=='lower_cells')return{label:'Find cell access',action:'go("node")',cls:'pri'};return{label:'Reach lower cells',action:'routeTo("lower_cells")',cls:'good'}}if(S.prisonerContact&&!S.prisonerOutcome)return S.node=='sealed_prisoner_cell'?{label:'Decide fate',action:'go("node")',cls:'pri'}:{label:'Return to prisoner',action:'routeTo("sealed_prisoner_cell")',cls:'good'};if(hasFlag('extraction_pressure'))return{label:'Escape or submit',action:'escapeOrCapture()',cls:'bad'};if(S.prisonerOutcome&&!S.aftermath)return{label:'Resolve chapter',action:'resolveGreyhook()',cls:'pri'};return{label:'Open Case Board',action:'go("board")',cls:'good'}}
currentObjective=function(){if(!S.contract&&!S.greyhook)return 'Start a new investigation: accept The Sealed Ledger.';if(S.ledger)return 'The ledger is recovered. Choose which faction receives it to open Greyhook.';if(S.contract&&!S.ledger)return 'Recover the Ledger at the Old Watchtower. Investigate at least one route if the way feels blocked.';if(S.aftermath||hasFlag('greyhook_resolved'))return 'Greyhook is resolved. Follow the Dead-Name Index hook into the Synod Archive.';if(S.greyhook&&!S.greyhookInside)return 'Reach Greyhook Fortress and commit to an entry route.';if(S.greyhookInside&&!S.prisonerContact)return 'Reach the sealed prisoner through Greyhook interior pressure.';if(S.prisonerContact&&!S.prisonerOutcome)return 'Decide prisoner fate: question, extract, silence, or trade.';if(hasFlag('extraction_pressure'))return 'Extraction has started. Escape, submit to capture, or use the escape route.';return 'Greyhook has an outcome. Resolve the chapter and carry the consequence forward.'};
recommendedNext=function(){if(S.party.length<3&&!S.contract&&!S.greyhook)return 'Choose three companions to begin the road.';if(!S.contract&&!S.greyhook)return 'Accept The Sealed Ledger from the Case Board.';if(S.ledger)return 'Resolve the ledger with a faction to unlock Greyhook Fortress.';if(S.contract&&!S.ledger){if(hasChapterSolution('sealed_ledger'))return 'Go to Old Watchtower and recover the ledger.';let l=nextLead('sealed_ledger');return l?`Investigate ${l[1].name} at ${n(l[1].node).name}.`:'Find one viable route, then recover the ledger at Old Watchtower.'}if(S.aftermath||hasFlag('greyhook_resolved'))return `Follow the next story hook: ${V.chapters.greyhook_fortress.nextHook}.`;if(S.greyhook&&!S.greyhookInside){if(hasGreyhookEntryRoute())return 'Go to Greyhook Gate and commit to a viable entry route.';let l=nextLead('greyhook_fortress');return l?`Investigate ${l[1].name} at ${n(l[1].node).name}.`:'Use the captured-inside route if no clean route is ready.'}if(S.greyhookInside&&!S.prisonerContact)return S.node=='sealed_prisoner_cell'?'Speak to the sealed prisoner.':S.node=='lower_cells'?'Use a lower-cell scene to reach the sealed prisoner.':'Reach Lower Cells from the Greyhook interior.';if(S.prisonerContact&&!S.prisonerOutcome)return 'Choose the prisoner fate. The Case Board shows the risks.';if(hasFlag('extraction_pressure'))return 'Use the escape route if prepared; otherwise capture becomes the failed-forward route.';if(S.prisonerOutcome&&!S.aftermath)return 'Resolve the Greyhook chapter and carry the consequence forward.';return `Next story hook: ${V.chapters.greyhook_fortress.nextHook}.`};
guideAction=function(){if(S.party.length<3&&!S.contract&&!S.greyhook)return{label:'Choose company',action:'go("party")',cls:'pri'};if(!S.contract&&!S.greyhook)return{label:'Accept case',action:'acceptLedger()',cls:'pri'};if(S.ledger)return{label:'Choose faction',action:'go("board")',cls:'pri'};if(S.contract&&!S.ledger){if(hasChapterSolution('sealed_ledger'))return{label:'Recover ledger',action:'routeTo("tower")',cls:'pri'};let leadEntry=nextLead('sealed_ledger');if(leadEntry){let[k,l]=leadEntry;return S.node==l.node?{label:'Investigate lead',action:`investigate('${k}')`,cls:'pri'}:{label:'Travel to lead',action:`routeTo('${l.node}')`,cls:'good'}}return{label:'Open Case Board',action:'go("board")',cls:'good'}}if(S.aftermath||hasFlag('greyhook_resolved'))return S.node=='synod_archive'?{label:'Study archive hook',action:'scene("archive_hook")',cls:'good'}:{label:'Go to Synod Archive',action:'routeTo("synod_archive")',cls:'good'};if(S.greyhook&&!S.greyhookInside){if(hasGreyhookEntryRoute())return S.node=='greyhook_gate'?{label:'Choose entry route',action:'go("node")',cls:'pri'}:{label:'Go to Greyhook Gate',action:'routeTo("greyhook_gate")',cls:'good'};let leadEntry=nextLead('greyhook_fortress');if(leadEntry){let[k,l]=leadEntry;return S.node==l.node?{label:'Investigate route',action:`investigate('${k}')`,cls:'pri'}:{label:'Travel to route',action:`routeTo('${l.node}')`,cls:'good'}}return{label:'Use captured route',action:'enterGreyhook("captured")',cls:'bad'}}if(S.greyhookInside&&!S.prisonerContact){if(S.node=='sealed_prisoner_cell')return{label:'Speak to prisoner',action:'prisonerContact()',cls:'pri'};if(S.node=='lower_cells')return{label:'Find cell access',action:'go("node")',cls:'pri'};return{label:'Reach lower cells',action:'routeTo("lower_cells")',cls:'good'}}if(S.prisonerContact&&!S.prisonerOutcome)return S.node=='sealed_prisoner_cell'?{label:'Decide fate',action:'go("node")',cls:'pri'}:{label:'Return to prisoner',action:'routeTo("sealed_prisoner_cell")',cls:'good'};if(hasFlag('extraction_pressure'))return{label:'Escape or submit',action:'escapeOrCapture()',cls:'bad'};if(S.prisonerOutcome&&!S.aftermath)return{label:'Resolve chapter',action:'resolveGreyhook()',cls:'pri'};return{label:'Open Case Board',action:'go("board")',cls:'good'}};
function guidePanel(){let a=guideAction();return `<div class="guidePanel"><div><div class="guideKicker">Current objective</div><div class="guideText">${recommendedNext()}</div></div><button class="btn mini ${a.cls||''}" onclick="${act(a.action)}">${a.label}</button></div>`}
function leadCheckLine(l){let score=checkScore(l),target=Math.max(0,l.dc-1),ready=score>=target;return `${tag(ready?'ready':'risky',ready?'green':'red')} score ${score} / ${target}+ using ${l.stat.toUpperCase()}`}
function routeCardAction(k,l,state){if(['unknown','failed_forward'].includes(state))return '';if(S.node==l.node&&state!='viable')return btn('Investigate now',`investigate('${k}')`,'pri');return btn('Travel to '+n(l.node).name,`routeTo('${l.node}')`,'good')}
routeCards=function(chapter){return Object.entries(D.leads).filter(([,l])=>l.chapter==chapter).map(([k,l])=>{let state=S.leads[k]||'unknown',body=`${l.text}<br><b>Where:</b> ${n(l.node).name} â€¢ <b>Check:</b> ${l.stat.toUpperCase()} ${l.dc}<br>${leadCheckLine(l)}<br><b>Reward:</b> ${l.item?item(l.item).name:'none'}<br><b>State:</b> ${tag(state,state=='viable'?'green':state=='failed_forward'?'red':state=='rumored'?'gold':'')}${l.transformsTo?'<br><b>Failed-forward:</b> '+l.transformsTo.map(x=>D.leads[x]?.name||x).join(', '):''}`;return card(l.name,body,routeCardAction(k,l,state))}).join('')};
prisonerButtons=function(){if(S.prisonerOutcome)return card('Prisoner fate locked',`${S.prisonerChoice}: ${S.prisonerOutcome}`,btn('Resolve Greyhook chapter','resolveGreyhook()','pri'));let s=S.prisonerContact?'':btn('Speak to sealed prisoner','prisonerContact()','pri');return s+['question','extract','silence','trade'].map(c=>btn(`${V.prisonerChoices[c].label} prisoner`,`prisonerChoice('${c}')`,c=='question'?'good':c=='extract'?'pri':'bad')).join('')};
nextStep=function(){let a=guideAction();return card('Next',recommendedNext(),`<button class="btn ${a.cls||''}" onclick="${act(a.action)}">${a.label}</button>`)};
function findPath(start,target){if(!D.nodes[target])return null;let queue=[[start]],seen=new Set([start]);while(queue.length){let path=queue.shift(),last=path[path.length-1];if(last==target)return path;for(const exit of n(last).exits){if(seen.has(exit)||!canUseExitFrom(last,exit))continue;seen.add(exit);queue.push([...path,exit])}}return null}
function spendTravel(steps=1){let fed=Math.min(S.res.food,steps);S.res.food-=fed;let hungry=steps-fed;if(hungry>0){S.res.heat+=hungry;addClue('Hungry travel raises heat. Forage or rest at camp before long routes.')}}
travel=function(id){if(!canUseExit(id)){raiseGreyhookAlert(1,'attempted movement during lockdown');log('Lockdown blocks the clean exit. Use escape, capture, patrol, or a companion route.');go('board');return}spendTravel(1);S.node=id;S.fatigue=(S.fatigue||0)+1;let m=tmeta(S.node);if(m.danger>=4){S.res.heat=Math.min(6,(S.res.heat||0)+1);addClue('Hostile territory raises heat.')}if(m.danger>=3&&S.fatigue>=5)addClue('Dangerous road while exhausted.');log('Travelled to '+n(id).name+'. Fatigue '+S.fatigue+'/6.');if(id=='grey_road'&&S.greyhook)addClue('Greyhook Road: choose a route card before trusting the gate.');go('node');if(T?.roadEvents)maybeRoadEvent()}; window.travel=travel;
routeTo=function(id){if(id==S.node){go('node');return}let path=findPath(S.node,id);if(!path){log('No clear route to '+n(id).name+' from here. Use the map or resolve lockdown pressure.');go('map');return}let steps=path.slice(1);spendTravel(steps.length);S.node=id;S.fatigue=(S.fatigue||0)+steps.length;if(steps.includes('grey_road')&&S.greyhook)addClue('Greyhook Road: choose a route card before trusting the gate.');log('Followed route to '+n(id).name+': '+path.map(x=>n(x).name).join(' -> ')+'. Fatigue '+S.fatigue+'/6.');go('node');if(T?.roadEvents)maybeRoadEvent()}; window.routeTo=routeTo;
title=function(){app.innerHTML=header()+`<div class="panel"><h2>v0.8.0-dev1 â€” Greyhook Complete Flow Pass</h2><p>The first full Greyhook flow pass: route families, alert ladder, interior scenes, prisoner fate, companion reactions, aftermath, and next chapter hook.</p>${btn('New Game','reset()','pri')}${btn(hasStoredSave()?'Continue':'Start from party draft','continueGame()','good')}${btn('Jump to Greyhook test state','devGreyhook()')}</div>`};
map=function(){let exits=n(S.node).exits;let line=(a,b)=>{let A=pos[a],B=pos[b],x=A[0]+42,y=A[1]+23,dx=B[0]-A[0],dy=B[1]-A[1],l=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;return `<div class="road" style="left:${x}px;top:${y}px;width:${l}px;transform:rotate(${ang}deg)"></div>`};let nodes=Object.keys(D.nodes).map(id=>`<div class="node ${id==S.node?'cur':exits.includes(id)?'avail':''} ${hasLeadAt(id)?'leadnode':''}" style="left:${pos[id][0]}px;top:${pos[id][1]}px" onclick="${id==S.node?'go(\'node\')':exits.includes(id)?`travel(\'${id}\')`:''}">${n(id).name}</div>`).join('');app.innerHTML=header()+`<div class="panel">${guidePanel()}<h2>Map</h2><div class="mapViewport"><div class="map">${roads.map(r=>line(r[0],r[1])).join('')}${nodes}</div></div>${btn('Current node','go("node")','pri')}${btn('Case Board','go("board")','good')}</div><div class="panel"><h2>Road Log</h2><div class="log">${S.log.map(x=>'â€¢ '+x+'<br>').join('')}</div></div>`};
nodeScreen=function(){app.innerHTML=header()+`<div class="panel">${guidePanel()}<h2>${n(S.node).name}</h2><p>${nodeText()}</p>${nodeActions()}<h3>Roads</h3>${n(S.node).exits.map(id=>btn('Travel to '+n(id).name,`travel('${id}')`,canUseExit(id)?'':'bad')).join('')}</div>`};
nodeActions=function(){let s='';let ls=Object.entries(D.leads).filter(([k,l])=>l.node==S.node&&S.leads[k]=='rumored');if(ls.length)s+=ls.map(([k,l])=>btn('Investigate: '+l.name+' ('+checkScore(l)+'/'+Math.max(0,l.dc-1)+')',`investigate('${k}')`,'good')).join('');if(S.node=='tower'&&S.contract&&!S.ledger)s+=btn('Take the ledger by force or parley','ledgerWin()','pri');if(S.node=='greyhook_gate')s+=greyhookApproaches()+sceneButtonsForNode('greyhook_gate');if(S.node=='greyhook_outer_yard')s+=sceneButtonsForNode('greyhook_outer_yard')+btn('Ask companion for Greyhook angle','companionAngle()','good')+btn('Starting enemy interference','enemyInterferenceScene()','bad');if(['quartermaster_tent','fortress_infirmary','lower_cells','synod_archive'].includes(S.node))s+=sceneButtonsForNode(S.node);if(S.node=='sealed_prisoner_cell')s+=sceneButtonsForNode('sealed_prisoner_cell')+prisonerButtons();if(isGreyhookLockdown())s+=btn('Forced escape / capture pressure','escapeOrCapture()','bad');return s||btn('Gather rumor','rumor()')};
company=function(){app.innerHTML=header()+`<div class="panel">${guidePanel()}<h2>Company</h2>${S.party.map(id=>{let c=comp(id);return card(`${c.name} â€” ${c.role}`,`${c.text}<br><b>${c.ability}:</b> ${c.effect}<br>${(c.tags||[]).map(x=>tag(x)).join('')}`)}).join('')}<h3>Morale</h3>${tag(S.morale||0,S.morale<0?'red':'green')}<h3>Companion Reactions</h3>${reactionCards()||'<p>No major reaction yet.</p>'}<h3>Crimes</h3>${S.crimes.map(c=>tag(c,'red')).join('')||'<p>No recorded crimes.</p>'}</div>`};
pack=function(){app.innerHTML=header()+`<div class="panel">${guidePanel()}<h2>Pack & Papers</h2>${S.items.map(id=>{let i=item(id);return card(`${i.name} â€” ${i.type}`,`${i.text}<br>${(i.tags||[]).map(x=>tag(x)).join('')}`)}).join('')||'<p>No special items yet.</p>'}</div>`};
camp=function(){let fat=tag(`Fatigue ${S.fatigue||0}/6`,S.fatigue>=5?'red':S.fatigue>=3?'purple':'');let wnd=tag(`Wounds ${S.wounds||0}`,S.wounds>0?'red':'');app.innerHTML=header()+`<div class="panel">${guidePanel()}<h2>Camp</h2>${fat} ${wnd}<br>${btn('Scout a rumor','rumor()')}${btn('Forage for food','forage()','good')}${btn('Plan Greyhook escape / reduce alert','campEscape()')}${btn('Debrief prisoner choice','campDebrief()')}${btn('Rest and eat','rest()')}<h3>Save</h3>${btn('Export save code','exportSave()','good')}${btn('Import save code','importSave()')}${btn('Reset run','confirmReset()','bad')}<h3>Debug</h3>${debugStatePanel()}</div>`};
header=function(){return `<div class="head"><div><h1>Gravesmoke Road</h1><div class="mut">v${D.version} - Day ${S.res.day} - ${n(S.node).name}</div></div>${resourceRail()}</div>`};
routeCards=function(chapter){return Object.entries(D.leads).filter(([,l])=>l.chapter==chapter).map(([k,l])=>{let state=S.leads[k]||'unknown',body=`${l.text}<br><b>Where:</b> ${n(l.node).name} - <b>Check:</b> ${l.stat.toUpperCase()} ${l.dc}<br>${leadCheckLine(l)}<br><b>Reward:</b> ${l.item?item(l.item).name:'none'}<br><b>State:</b> ${tag(state,state=='viable'?'green':state=='failed_forward'?'red':state=='rumored'?'gold':'')}${l.transformsTo?'<br><b>Failed-forward:</b> '+l.transformsTo.map(x=>D.leads[x]?.name||x).join(', '):''}`;return card(l.name,body,routeCardAction(k,l,state))}).join('')};
title=function(){app.innerHTML=header()+`<div class="panel"><h2>v0.8.0-dev1 - Greyhook Complete Flow Pass</h2><p>The first full Greyhook flow pass: route families, alert ladder, interior scenes, prisoner fate, companion reactions, aftermath, and next chapter hook.</p>${btn('New Game','reset()','pri')}${btn(hasStoredSave()?'Continue':'Start from party draft','continueGame()','good')}${btn('Jump to Greyhook test state','devGreyhook()')}</div>`};
map=function(){let exits=n(S.node).exits;let line=(a,b)=>{let A=pos[a],B=pos[b],x=A[0]+42,y=A[1]+23,dx=B[0]-A[0],dy=B[1]-A[1],l=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;return `<div class="road" style="left:${x}px;top:${y}px;width:${l}px;transform:rotate(${ang}deg)"></div>`};let nodes=Object.keys(D.nodes).map(id=>`<div class="node ${id==S.node?'cur':exits.includes(id)?'avail':''} ${hasLeadAt(id)?'leadnode':''}" style="left:${pos[id][0]}px;top:${pos[id][1]}px" onclick="${id==S.node?'go(\'node\')':exits.includes(id)?`travel(\'${id}\')`:''}">${n(id).name}</div>`).join('');app.innerHTML=header()+`<div class="panel">${guidePanel()}<h2>Map</h2><div class="mapViewport"><div class="map">${roads.map(r=>line(r[0],r[1])).join('')}${nodes}</div></div>${btn('Current node','go("node")','pri')}${btn('Case Board','go("board")','good')}</div><div class="panel"><h2>Road Log</h2><div class="log">${S.log.map(x=>'- '+x+'<br>').join('')}</div></div>`};
company=function(){app.innerHTML=header()+`<div class="panel">${guidePanel()}<h2>Company</h2>${S.party.map(id=>{let c=comp(id);return card(`${c.name} - ${c.role}`,`${c.text}<br><b>${c.ability}:</b> ${c.effect}<br>${(c.tags||[]).map(x=>tag(x)).join('')}`)}).join('')}<h3>Morale</h3>${tag(S.morale||0,S.morale<0?'red':'green')}<h3>Companion Reactions</h3>${reactionCards()||'<p>No major reaction yet.</p>'}<h3>Crimes</h3>${S.crimes.map(c=>tag(c,'red')).join('')||'<p>No recorded crimes.</p>'}</div>`};
pack=function(){app.innerHTML=header()+`<div class="panel">${guidePanel()}<h2>Pack & Papers</h2>${S.items.map(id=>{let i=item(id);return card(`${i.name} - ${i.type}`,`${i.text}<br>${(i.tags||[]).map(x=>tag(x)).join('')}`)}).join('')||'<p>No special items yet.</p>'}</div>`};
map=function(){let exits=n(S.node).exits,scale=1.38,pad=24,pt=id=>[Math.round(pos[id][0]*scale+pad),Math.round(pos[id][1]*scale+pad)];let line=(a,b)=>{let A=pt(a),B=pt(b),x=A[0]+43,y=A[1]+23,dx=B[0]-A[0],dy=B[1]-A[1],l=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;return `<div class="road" style="left:${x}px;top:${y}px;width:${l}px;transform:rotate(${ang}deg)"></div>`};let nodes=Object.keys(D.nodes).map(id=>{let P=pt(id);return `<div class="node ${id==S.node?'cur':exits.includes(id)?'avail':''} ${hasLeadAt(id)?'leadnode':''}" style="left:${P[0]}px;top:${P[1]}px" onclick="${id==S.node?'go(\'node\')':exits.includes(id)?`travel(\'${id}\')`:''}">${n(id).name}</div>`}).join('');app.innerHTML=header()+`<div class="panel">${guidePanel()}<h2>Map</h2><div class="mapViewport"><div class="map">${roads.map(r=>line(r[0],r[1])).join('')}${nodes}</div></div>${btn('Current node','go("node")','pri')}${btn('Case Board','go("board")','good')}</div><div class="panel"><h2>Road Log</h2><div class="log">${S.log.map(x=>'- '+x+'<br>').join('')}</div></div>`};
function centerMapOnCurrent(){let vp=app.querySelector('.mapViewport'),cur=app.querySelector('.node.cur');if(!vp||!cur)return;vp.scrollLeft=Math.max(0,cur.offsetLeft-vp.clientWidth/2+cur.clientWidth/2);vp.scrollTop=Math.max(0,cur.offsetTop-vp.clientHeight/2+cur.clientHeight/2)}
const renderPlayableMap=map;
map=function(){renderPlayableMap();setTimeout(centerMapOnCurrent,0)};
const mapLayout={gate:[250,28],market:[360,125],inn:[486,182],chapel:[250,172],ditch:[70,150],road:[170,270],tower:[318,330],mill:[70,365],ford:[485,365],shrine:[230,338],grey_road:[250,455],muster_field:[86,455],quartermaster_tent:[86,292],greyhook_gate:[500,455],greyhook_outer_yard:[370,350],fortress_infirmary:[590,336],synod_archive:[590,210],lower_cells:[392,236],sealed_prisoner_cell:[392,82]};
map=function(){let exits=n(S.node).exits,pt=id=>mapLayout[id]||pos[id];let line=(a,b)=>{let A=pt(a),B=pt(b),x=A[0]+43,y=A[1]+23,dx=B[0]-A[0],dy=B[1]-A[1],l=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;return `<div class="road" style="left:${x}px;top:${y}px;width:${l}px;transform:rotate(${ang}deg)"></div>`};let nodes=Object.keys(D.nodes).map(id=>{let P=pt(id);return `<div class="node ${id==S.node?'cur':exits.includes(id)?'avail':''} ${hasLeadAt(id)?'leadnode':''}" style="left:${P[0]}px;top:${P[1]}px" onclick="${id==S.node?'go(\'node\')':exits.includes(id)?`travel(\'${id}\')`:''}">${n(id).name}</div>`}).join('');app.innerHTML=header()+`<div class="panel">${guidePanel()}<h2>Map</h2><div class="mapViewport"><div class="map">${roads.map(r=>line(r[0],r[1])).join('')}${nodes}</div></div>${btn('Current node','go("node")','pri')}${btn('Case Board','go("board")','good')}</div><div class="panel"><h2>Road Log</h2><div class="log">${S.log.map(x=>'- '+x+'<br>').join('')}</div></div>`;setTimeout(centerMapOnCurrent,0)};
function forage(){S.res.food+=2;S.res.day++;S.res.heat=Math.min(6,S.res.heat+1);log('Foraged for food. Heat rises as the road notices you.');render()} window.forage=forage;
rest=function(){let ate=S.res.food>0;S.res.food=Math.max(0,S.res.food-1);S.res.day++;S.res.heat=Math.max(0,S.res.heat-1);S.fatigue=Math.max(0,(S.fatigue||0)-2);if(S.perks.includes('camp_surgeon'))S.res.medicine=Math.max(0,(S.res.medicine||0)+1);if(ate&&S.morale<2)S.morale++;log(ate?'Rested, ate, and cooled the trail. Fatigue: '+S.fatigue+'/6.':'Rested hungry; heat cools, morale does not.');render()}; window.rest=rest;
function encodeSave(data){let bytes=new TextEncoder().encode(JSON.stringify(data));let text='';bytes.forEach(b=>text+=String.fromCharCode(b));return btoa(text)}
function decodeSave(code){let text=atob(code.trim());let bytes=Uint8Array.from(text,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
function exportSave(){let payload=encodeSave(S),done=()=>{log('Save code exported.');render()};if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(payload).then(done).catch(()=>{prompt('Copy save code',payload);done()});else{prompt('Copy save code',payload);done()}} window.exportSave=exportSave;
function importSave(){let payload=prompt('Paste save code');if(!payload||!payload.trim())return;try{let data=decodeSave(payload.trim());if(!data||typeof data!=='object')throw new Error('Invalid save data');let restored=hydrate(data);S=restored;log('Save code imported.');render()}catch(e){alert('Save import failed. Current save is unchanged.');log('Save import failed.');render()}} window.importSave=importSave;
function confirmReset(){if(confirm('Reset this run and return to party selection?'))reset()} window.confirmReset=confirmReset;

function debugStateText(){return [
  `Gravesmoke Road v${D.version}`,
  `Character: ${S.name||'?'}  Origin: ${S.origin||'none'}  Lv ${S.level}  XP ${S.xp||0}`,
  `Perks: ${S.perks.join(', ')||'none'}  Perk pts: ${S.perkPoints}`,
  `Screen: ${S.screen}  Node: ${S.node}  Settlement: ${S.settlement||'none'}`,
  `Party: ${S.party.join(', ')||'none'}  Morale: ${S.morale}`,
  `Food: ${S.res.food}  Fatigue: ${S.fatigue||0}/6  Heat: ${S.res.heat}/6  Day: ${S.res.day}  Coin: ${S.res.coin}`,
  `Greyhook inside: ${S.greyhookInside?'yes':'no'}  Route: ${S.greyhookRoute||'none'}  Alert: ${S.greyhookAlert}/5`,
  `Prisoner contact: ${S.prisonerContact?'yes':'no'}  Choice: ${S.prisonerChoice||'none'}  Outcome: ${S.prisonerOutcome||'none'}`,
  `Aftermath: ${S.aftermath||'none'}  Flags: ${Object.keys(S.flags).length}  Items: ${S.items.length}  Solutions: ${S.solutions.length}`,
  `Crimes: ${S.crimes.length}  Enemy type: ${S.enemyType}  Pressure: ${S.enemyPressure}`,
  `Wounds: ${S.wounds||0}  Last routes: ${S.routeHistory.slice(-5).join(', ')||'none'}`
].join('\n')}
function copyDebugState(){let t=debugStateText();let done=()=>log('Debug state copied.');let fail=()=>{let el=document.querySelector('.debugDetails');if(el)el.open=true;log('Copy unavailable. Raw state visible below.')};if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(t).then(done).catch(fail);else fail();render()} window.copyDebugState=copyDebugState;
function debugStatePanel(){let rows=[
  ['Version',D.version,'Save',String(S.saveVersion||'?')],
  ['Name',S.name||'?','Origin',S.origin||'none'],
  ['Level',String(S.level),'XP',`${S.xp||0}`],
  ['Perks',S.perks.join(', ')||'none','Points',String(S.perkPoints)],
  ['Screen',S.screen,'node',n(S.node).name],
  ['Party',S.party.join(', ')||'none','Morale',String(S.morale)],
  ['Food',String(S.res.food),'Fatigue',`${S.fatigue||0}/6`],
  ['Heat',`${S.res.heat}/6`,'Day',String(S.res.day)],
  ['Coin',String(S.res.coin),'Med',String(S.res.medicine)],
  ['Greyhook inside',S.greyhookInside?'yes':'no','Route',S.greyhookRoute||'none'],
  ['Alert',`${S.greyhookAlert}/5 — ${greyhookAlertBand()}`,'Lockdown',isGreyhookLockdown()?'yes':'no'],
  ['Prisoner contact',S.prisonerContact?'yes':'no','Choice',S.prisonerChoice||'none'],
  ['Outcome',S.prisonerOutcome||'none','Aftermath',S.aftermath||'none'],
  ['Flags',String(Object.keys(S.flags).length),'Items',String(S.items.length)],
  ['Solutions',String(S.solutions.length),'Clues',String(S.clues.length)],
  ['Crimes',String(S.crimes.length),'Reactions',String(S.reactions.length)],
  ['Wounds',String(S.wounds||0),'Enemy',S.enemyType],
  ['Last routes',S.routeHistory.slice(-5).join(', ')||'none','']
];let table=rows.map(r=>`<tr>${r.map(c=>c?`<td>${escapeHtml(String(c))}</td>`:'<td></td>').join('')}</tr>`).join('');return `<div class="card debugPanel"><div class="ct">Debug State</div><table class="debugTable">${table}</table><details class="debugDetails"><summary>Raw State</summary><pre class="errorStack">${escapeHtml(JSON.stringify(S,null,2))}</pre></details>${btn('Copy Debug State','copyDebugState()','good')}${S.greyhookInside||!S.greyhook?'':btn('Jump to Greyhook test state','devGreyhook()')}${btn('Reset Save','confirmReset()','bad')}</div>`}

function actionGroup(title,html,cls=''){if(!html)return '';let key=cls.includes('danger')?'danger':cls.includes('travel')?'travel':cls.includes('scene')?'investigate':'resolve';return `<section class="actionGroup ${cls}"><div class="groupTitle">${assetImg(iconEntry(key),'groupIcon','')}<span>${title}</span></div><div class="actionGrid">${html}</div></section>`}
function resourcePill(label,value,cls='',icon='action'){return `<span class="resourcePill ${cls}">${assetImg(iconEntry(icon),'pillIcon','')}<span>${label}</span><b>${value}</b></span>`}
resourceRail=function(){let parts=[resourcePill('coin',S.res.coin,'gold','paper'),resourcePill('food',S.res.food,S.res.food<=1?'red':'','camp'),resourcePill('fatigue',`${S.fatigue||0}/6`,S.fatigue>=5?'red':S.fatigue>=3?'purple':'','travel'),resourcePill('heat',S.res.heat,S.res.heat>=4?'red':'','warning')];if(S.greyhook)parts.push(resourcePill('Greyhook',`${S.greyhookAlert}/5`,S.greyhookAlert>=4?'red':'purple','danger'));if(S.morale)parts.push(resourcePill('morale',S.morale,S.morale<0?'red':'green','company'));return `<div class="resourceRail">${parts.join('')}</div>`};
header=function(){return `<div class="head"><div><h1>Gravesmoke Road</h1><div class="mut">v${D.version} - Day ${S.res.day} - ${n(S.node).name}</div></div>${resourceRail()}</div>`};
guidePanel=function(){let a=guideAction();return `<div class="guidePanel"><div><div class="guideKicker">Current objective</div><div class="guideText">${recommendedNext()}</div></div>${btn(a.label,a.action,`mini ${a.cls||''}`)}</div>`};

function nodeActionGroups(){let g={primary:'',scene:'',danger:''};let ls=Object.entries(D.leads).filter(([k,l])=>l.node==S.node&&S.leads[k]=='rumored');if(ls.length)g.scene+=ls.map(([k,l])=>btn('Investigate: '+l.name+' ('+checkScore(l)+'/'+Math.max(0,l.dc-1)+')',`investigate('${k}')`,'good')).join('');if(S.node=='tower'&&S.contract&&!S.ledger)g.primary+=btn('Take the ledger by force or parley','ledgerWin()','pri');if(S.node=='greyhook_gate'){g.primary+=greyhookApproaches();g.scene+=sceneButtonsForNode('greyhook_gate')}if(S.node=='greyhook_outer_yard'){g.scene+=sceneButtonsForNode('greyhook_outer_yard');g.primary+=btn('Ask companion for Greyhook angle','companionAngle()','good');g.danger+=btn('Starting enemy interference','enemyInterferenceScene()','bad')}if(['quartermaster_tent','fortress_infirmary','lower_cells','synod_archive'].includes(S.node))g.scene+=sceneButtonsForNode(S.node);if(S.node=='sealed_prisoner_cell')g.primary+=sceneButtonsForNode('sealed_prisoner_cell')+prisonerButtons();if(isGreyhookLockdown())g.danger+=btn('Forced escape / capture pressure','escapeOrCapture()','bad');if(!g.primary&&!g.scene&&!g.danger)g.scene+=btn('Gather rumor','rumor()');return g}
function renderActionGroups(g){return actionGroup('Primary',g.primary,'primary')+actionGroup('Scene',g.scene,'scene')+actionGroup('Danger',g.danger,'danger')}
nodeActions=function(){return renderActionGroups(nodeActionGroups())};
nodeScreen=function(){let exits=n(S.node).exits.map(id=>btn('Travel to '+n(id).name,`travel('${id}')`,canUseExit(id)?'':'bad')).join('');let settleId=withinSettlement(),settleBtn=settleId?btn('Enter '+settle(settleId).name,`go('settlement')`,'pri'):'';let fat=tag(`Fatigue ${S.fatigue||0}/6`,S.fatigue>=5?'red':S.fatigue>=3?'purple':'');let danger=tmeta(S.node).danger>=4?tag('Hostile','red'):tmeta(S.node).danger>=3?tag('Dangerous','purple'):'';app.innerHTML=header()+`<div class="panel playPanel">${guidePanel()}${scenePanel(S.node)}<div class="locationBlock"><div class="guideKicker">Current location</div><h2>${n(S.node).name}</h2><p>${nodeText()}</p>${settleBtn}<div>${fat} ${danger}</div></div>${nodeActions()}${actionGroup('Travel',exits,'travel')}</div>`};

party=function(){let choices=S.pool.map(id=>{let c=comp(id);return `<div class="choice partyChoice ${S.party.includes(id)?'sel':''}" onclick="pickComp('${id}')">${portraitImg(id,'choicePortrait')}<div><div class="ct">${c.name} - ${c.role}</div><div class="cx">${c.text}<br><b>${c.ability}:</b> ${c.effect}<br>${(c.tags||[]).map(x=>tag(x)).join('')}</div></div></div>`}).join('');app.innerHTML=header()+`<div class="panel"><h2>Choose three companions</h2><p class="mut">Companions open Greyhook routes and react to prisoner fate.</p><div class="partyGrid">${choices}</div>${S.party.length==3?btn('Begin at Gallowsford Gate','go("map")','pri'):''}</div>`};
function companionCard(id){let c=comp(id),st=S.companionState[id]||{loyalty:0,stress:0,wound:0};let loyalty=st.loyalty>0?tag('loyal '+st.loyalty,'green'):st.loyalty<0?tag('disloyal '+(-st.loyalty),'red'):'';let stress=st.stress>0?tag('stress '+st.stress,'purple'):'';return `<div class="card companionCard">${portraitImg(id)}<div><div class="ct">${c.name} - ${c.role}</div><div class="cx">${c.text}<br><b>${c.ability}:</b> ${c.effect}<br>${(c.tags||[]).map(x=>tag(x)).join('')}${loyalty}${stress}</div></div></div>`}
function characterSheet(){let o=origin(S.origin),nextXp=P?.xpThresholds?.[S.level]||0;let xpPct=nextXp>0?Math.min(100,Math.floor((S.xp||0)/nextXp*100)):0;let xpBar=`<span class="xpBar"><span>XP ${S.xp||0}/${nextXp}</span><span class="xpFill" style="width:${xpPct}%"></span></span>`;return card('Character',`<b>${S.name||'Nameless'}</b> - ${S.backgroundTitle||''}<br>Origin: ${S.origin||'none'}<br>Level ${S.level} ${xpBar}<br>${Object.entries(S.stats).map(([k,v])=>tag(k+' '+v)).join('')}<br>Wounds: ${S.wounds||0}  Fatigue: ${S.fatigue||0}/6`)+perkList()}
company=function(){app.innerHTML=header()+`<div class="panel">${guidePanel()}${characterSheet()}<h2>Companions</h2>${S.party.map(companionCard).join('')||'<p>No companions selected.</p>'}<h3>Morale</h3>${tag(S.morale||0,S.morale<0?'red':'green')}<h3>Companion Reactions</h3>${reactionCards()||'<p>No major reaction yet.</p>'}<h3>Crimes</h3>${S.crimes.map(c=>tag(c,'red')).join('')||'<p>No recorded crimes.</p>'}</div>`};
function itemCard(id){let i=item(id);return `<div class="card itemCard">${itemIconHtml(i)}<div><div class="ct">${i.name} - ${i.type}</div><div class="cx">${i.text}<br>${(i.tags||[]).map(x=>tag(x)).join('')}</div></div></div>`}
pack=function(){app.innerHTML=header()+`<div class="panel">${guidePanel()}<h2>Pack & Papers</h2>${S.items.map(itemCard).join('')||'<p>No special items yet.</p>'}</div>`};
consequenceCards=function(){let f=Object.entries(S.fac).filter(([,v])=>v).map(([k,v])=>`<div class="factionRow">${factionMarkHtml(k)}<span>${D.factions[k].name}</span><b>${v>0?'+':''}${v}</b></div>`).join('')||'No faction shifts yet.';let c=S.crimes.length?S.crimes.map(x=>tag(x,'red')).join(''):'No recorded crimes.';let extra=S.consequenceLog.map(x=>card('Consequence',x)).join('');return card('Faction Changes',f)+card('Legal / Crime Record',c)+card('Party Morale',String(S.morale||0))+extra};
routeCards=function(chapter){return Object.entries(D.leads).filter(([,l])=>l.chapter==chapter).map(([k,l])=>{let state=S.leads[k]||'unknown',reward=l.item?`<span class="rewardLine">${itemIconHtml(l.item,'miniIcon')}${item(l.item).name}</span>`:'none',body=`${l.text}<br><b>Where:</b> ${n(l.node).name} - <b>Check:</b> ${l.stat.toUpperCase()} ${l.dc}<br>${leadCheckLine(l)}<br><b>Reward:</b> ${reward}<br><b>State:</b> ${tag(state,state=='viable'?'green':state=='failed_forward'?'red':state=='rumored'?'gold':'')}${l.transformsTo?'<br><b>Failed-forward:</b> '+l.transformsTo.map(x=>D.leads[x]?.name||x).join(', '):''}`;return card(l.name,body,routeCardAction(k,l,state))}).join('')};
nextStep=function(){let a=guideAction();return card('Next',recommendedNext(),btn(a.label,a.action,a.cls||''))};
title=function(){app.innerHTML=header()+`<div class="panel titlePanel">${scenePanel('gate')}<h2>v0.8.2-dev1 — RPG Foundation</h2><p>Character origins, XP/perks, road travel pressure, settlement hubs, companion depth.</p>${btn('New Game','reset()','pri')}${btn(hasStoredSave()?'Continue':'Start from saved draft','continueGame()','good')}${btn('Jump to Greyhook test state','devGreyhook()')}</div>`};

const navLabels={map:'Map',board:'Board',company:'Company',pack:'Pack',camp:'Camp'};
render=function(){save();nav.hidden=['title','origin','party'].includes(S.screen);if(!nav.hidden)nav.innerHTML=`<div class="navInner">${Object.keys(navLabels).map(x=>`<button class="${S.screen==x?'active':''}" onclick="go('${x}')">${navIcon(x)}<span>${navLabels[x]}</span></button>`).join('')}</div>`;try{({title,map,board,company,pack,camp,party,node:nodeScreen,settlement:settlementScreen,origin:originScreen}[S.screen]||map)()}catch(e){showRuntimeError(e,'render')}}; window.render=render;

try { render(); } catch(e) { showRuntimeError(e,'render'); }
