const D=await fetch('./data/game_data.json').then(r=>r.json());
const V=await fetch('./data/greyhook_v08.json').then(r=>r.json());
D.version=V.version;
const K='gravesmoke.repo.v080dev1';
const app=document.getElementById('app');
const nav=document.getElementById('nav');

const blank=()=>({
  screen:'title',node:'gate',log:[],party:[],pool:Object.keys(D.companions),
  stats:{body:5,wits:5,guile:5,presence:5,resolve:5},
  res:{coin:14,food:5,medicine:2,tools:2,heat:0,day:1},
  fac:{iron:0,rook:0,synod:0,free:0,hearth:0,veil:0,red:0},
  crimes:[],leads:{market_papers:'rumored',rookery_drain:'rumored',free_writ:'rumored',synod_rites:'rumored',refugee_witness:'rumored'},
  solutions:[],items:[],clues:['The sealed ledger exists.'],flags:{},contract:false,ledger:false,
  greyhook:false,greyhookInside:false,greyhookRoute:null,greyhookAlert:0,prisonerContact:false,
  prisonerChoice:null,prisonerOutcome:null,morale:0,reactions:[],aftermath:null,enemyType:'wanted',enemyPressure:0
});
let S=JSON.parse(localStorage.getItem(K)||JSON.stringify(blank()));
const save=()=>localStorage.setItem(K,JSON.stringify(S));
const n=id=>D.nodes[id];
const lead=id=>D.leads[id];
const item=id=>D.items[id];
const comp=id=>D.companions[id];
const btn=(t,a,c='')=>`<button class="btn ${c}" onclick="${a}">${t}</button>`;
const tag=(t,c='')=>`<span class="tag ${c}">${t}</span>`;

function log(t){S.log.unshift(t);S.log=S.log.slice(0,40)}
function addClue(t){if(t&&!S.clues.includes(t))S.clues.push(t)}
function addItem(id){if(id&&!S.items.includes(id))S.items.push(id)}
function addSol(id){if(id&&!S.solutions.includes(id))S.solutions.push(id)}
function setFlag(k,v=true){S.flags[k]=v}
function hasFlag(k){return !!S.flags[k]}
function deltaFac(d={}){for(const k of Object.keys(d))S.fac[k]=(S.fac[k]||0)+d[k]}
function go(x){S.screen=x;render()} window.go=go;
function reset(){S=blank();go('party')} window.reset=reset;
function devGreyhook(){S=blank();S.party=['mara','nell','ilyra'];S.greyhook=true;S.node='greyhook_gate';['greyhook_supply','greyhook_quartermaster','greyhook_infirmary','greyhook_transfer','greyhook_escape_route'].forEach(k=>S.leads[k]='rumored');addClue('Greyhook Fortress holds a sealed prisoner.');addSol('greyhook_supply_route');addSol('infirmary_route');log('Dev state: Greyhook vertical slice seeded.');go('board')} window.devGreyhook=devGreyhook;

function greyhookAlertBand(){let a=S.greyhookAlert||0;if(a<=1)return 'routine';if(a<=3)return 'tightened searches';if(a===4)return 'lockdown';return 'forced escape / capture'}
function greyhookAlertText(){let b=greyhookAlertBand();return b==='routine'?'Routine garrison behavior.':b==='tightened searches'?'Searches tighten; forged papers and visible weapons draw attention.':b==='lockdown'?'Lockdown: exits are risky and patrols control movement.':'Forced pressure: escape, surrender, fight, or use a special route.'}
function raiseAlert(n,why){S.greyhookAlert=Math.max(0,(S.greyhookAlert||0)+n);if(why)addClue(`Greyhook alert ${n>=0?'+':''}${n}: ${why}`);if(S.greyhookAlert>=4&&!S.leads.greyhook_escape_route){S.leads.greyhook_escape_route='rumored';addClue('Lockdown reveals a Greyhook escape-route lead.')}log(`Greyhook alert is now ${S.greyhookAlert}/5 — ${greyhookAlertBand()}.`)}
function canUseExit(id){if(!S.greyhookInside)return true;if(S.greyhookAlert<4)return true;return ['lower_cells','sealed_prisoner_cell','greyhook_outer_yard'].includes(S.node)||S.solutions.includes('greyhook_escape')||S.party.includes('mara')||S.party.includes('nell')}
function maybeEnemy(trigger){let e=V.enemyInterference[S.enemyType];if(!e||!e.triggers.includes(trigger))return;S.enemyPressure++;raiseAlert(1,e.effect);addClue(`${e.name} interference: ${e.effect}`);log(`${e.name} interferes at Greyhook.`)}
function companionReaction(choice){let map=V.companionReactions[choice]||{};for(const id of S.party){let text=map[id];if(text&&!S.reactions.includes(text)){S.reactions.push(text);addClue('Companion reaction: '+text)}}}

function header(){return `<div class="head"><h1>Gravesmoke Road</h1><div class="mut">v${D.version} • Day ${S.res.day} • ${n(S.node).name}<br>${tag('food '+S.res.food)}${tag('heat '+S.res.heat)}${S.greyhook?tag('Greyhook '+S.greyhookAlert+'/5: '+greyhookAlertBand(),'red'):''}</div></div>`}
function render(){save();nav.hidden=['title','party'].includes(S.screen);if(!nav.hidden)nav.innerHTML=`<div class="navInner">${['map','board','company','pack','camp'].map(x=>`<button class="${S.screen==x?'active':''}" onclick="go('${x}')">${x}</button>`).join('')}</div>`;({title,map,board,company,pack,camp,party,node:nodeScreen}[S.screen]||map)()} window.render=render;

function title(){app.innerHTML=header()+`<div class="panel"><h2>v0.8-dev1 — Greyhook Complete Flow Pass</h2><p>The first full vertical-slice pass: route families, alert ladder, interior scenes, prisoner fate, companion reactions, aftermath card, and next chapter hook.</p>${btn('New Game','reset()','pri')}${btn('Continue','go("map")','good')}${btn('Jump to Greyhook test state','devGreyhook()')}</div>`}
function party(){app.innerHTML=header()+`<div class="panel"><h2>Choose three companions</h2><p class="mut">Companions create routes and react to prisoner fate.</p>${S.pool.map(id=>{let c=comp(id);return `<div class="choice ${S.party.includes(id)?'sel':''}" onclick="pickComp('${id}')"><div class="ct">${c.name} — ${c.role}</div><div class="cx">${c.text}<br><b>${c.ability}:</b> ${c.effect}</div></div>`}).join('')}${S.party.length==3?btn('Begin at Gallowsford Gate','go("map")','pri'):''}</div>`}
function pickComp(id){S.party=S.party.includes(id)?S.party.filter(x=>x!=id):(S.party.length<3?[...S.party,id]:S.party);render()} window.pickComp=pickComp;

const pos={gate:[220,28],market:[305,105],inn:[390,170],chapel:[210,150],ditch:[80,130],road:[145,230],tower:[260,280],mill:[70,285],ford:[350,280],shrine:[185,265],grey_road:[245,335],muster_field:[105,330],quartermaster_tent:[90,235],greyhook_gate:[375,330],greyhook_outer_yard:[300,250],fortress_infirmary:[430,235],synod_archive:[420,140],lower_cells:[305,160],sealed_prisoner_cell:[305,80]};
const roads=[['gate','market'],['gate','ditch'],['gate','road'],['market','inn'],['market','chapel'],['chapel','shrine'],['ditch','road'],['ditch','shrine'],['road','tower'],['road','mill'],['mill','ford'],['inn','ford'],['road','grey_road'],['grey_road','muster_field'],['muster_field','quartermaster_tent'],['quartermaster_tent','greyhook_gate'],['grey_road','greyhook_gate'],['greyhook_gate','greyhook_outer_yard'],['greyhook_outer_yard','fortress_infirmary'],['greyhook_outer_yard','lower_cells'],['lower_cells','sealed_prisoner_cell'],['fortress_infirmary','synod_archive']];
function map(){let exits=n(S.node).exits;let line=(a,b)=>{let A=pos[a],B=pos[b],x=A[0]+42,y=A[1]+23,dx=B[0]-A[0],dy=B[1]-A[1],l=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;return `<div class="road" style="left:${x}px;top:${y}px;width:${l}px;transform:rotate(${ang}deg)"></div>`};let nodes=Object.keys(D.nodes).map(id=>`<div class="node ${id==S.node?'cur':exits.includes(id)?'avail':''} ${hasLeadAt(id)?'leadnode':''}" style="left:${pos[id][0]}px;top:${pos[id][1]}px" onclick="${id==S.node?'go(\'node\')':exits.includes(id)?`travel(\'${id}\')`:''}">${n(id).name}</div>`).join('');app.innerHTML=header()+`<div class="panel"><h2>Map</h2><div class="map">${roads.map(r=>line(r[0],r[1])).join('')}${nodes}</div>${btn('Current node','go("node")','pri')}${btn('Case Board','go("board")','good')}</div><div class="panel"><h2>Road Log</h2><div class="log">${S.log.map(x=>'• '+x+'<br>').join('')}</div></div>`}
function travel(id){if(!canUseExit(id)){raiseAlert(1,'attempted movement during lockdown');log('Lockdown blocks the clean exit. Use escape, capture, or patrol scenes.');render();return}S.node=id;S.res.food=Math.max(0,S.res.food-1);log('Travelled to '+n(id).name+'.');if(id=='greyhook_gate'&&!S.greyhook)addClue('Greyhook Fortress blocks the road to the sealed prisoner.');go('node')} window.travel=travel;
function hasLeadAt(id){return Object.entries(D.leads).some(([k,l])=>l.node==id&&S.leads[k]&&!['viable','used'].includes(S.leads[k]))}

function nodeText(){let t=n(S.node).desc;if(S.greyhook&&['greyhook_gate','greyhook_outer_yard','quartermaster_tent','fortress_infirmary','lower_cells','sealed_prisoner_cell','synod_archive'].includes(S.node))t+=' '+greyhookAlertText();return t}
function nodeScreen(){app.innerHTML=header()+`<div class="panel"><h2>${n(S.node).name}</h2><p>${nodeText()}</p>${nodeActions()}<h3>Roads</h3>${n(S.node).exits.map(id=>btn('Travel to '+n(id).name,`travel('${id}')`)).join('')}</div>`}
function nodeActions(){let s='';let ls=Object.entries(D.leads).filter(([k,l])=>l.node==S.node&&S.leads[k]&&!['viable','used'].includes(S.leads[k]));if(ls.length)s+=ls.map(([k,l])=>btn('Investigate: '+l.name,`investigate('${k}')`,'good')).join('');if(S.node=='tower'&&S.contract&&!S.ledger)s+=btn('Take the ledger by force or parley','ledgerWin()','pri');if(S.node=='greyhook_gate')s+=greyhookApproaches()+btn('Study gate search pattern','scene("gate_search")','good');if(S.node=='greyhook_outer_yard')s+=btn('Study yard patrols','scene("yard_patrols")','good')+btn('Ask companion for Greyhook angle','companionAngle()','good')+btn('Starting enemy interference','enemyScene()','bad');if(S.node=='quartermaster_tent')s+=btn('Search quartermaster lockbox','scene("quartermaster_lockbox")','good');if(S.node=='fortress_infirmary')s+=btn('Search infirmary records','scene("infirmary_records")','good')+btn('Respect weapon restriction','addSol("infirmary_route");addClue("Infirmary route strengthened by visible restraint.");render()','good');if(S.node=='lower_cells')s+=btn('Attempt lower-cell access','scene("lower_cell_access")','pri');if(S.node=='sealed_prisoner_cell')s+=btn('Speak to sealed prisoner','prisonerContact()','pri')+['question','extract','silence','trade'].map(c=>btn(V.prisonerChoices[c].label+' prisoner',`prisonerChoice('${c}')`,c=='question'?'good':c=='extract'?'pri':'bad')).join('');if(S.node=='synod_archive')s+=btn('Read Dead-Name Index scrap','scene("archive_hook")','good');if(S.greyhookAlert>=4)s+=btn('Patrol confrontation','patrol()','bad')+btn('Search for escape mark','escapeMark()','good');if(S.greyhookAlert>=5)s+=btn('Forced escape / capture pressure','escapeOrCapture()','bad');return s||btn('Gather rumor','rumor()')}

function board(){let leads=Object.entries(D.leads).map(([k,l])=>`<div class="card"><div class="ct">${l.name} — ${S.leads[k]||'unknown'} ${tag(l.chapter=='greyhook_fortress'?'Greyhook':'Ledger',l.chapter=='greyhook_fortress'?'blue':'gold')}</div><div class="cx">${l.text}<br><b>Where:</b> ${n(l.node).name} • <b>Check:</b> ${l.stat.toUpperCase()} ${l.dc}<br>${l.item?'<b>Reward:</b> '+item(l.item).name:''}${l.transformsTo?'<br><b>Failed-forward:</b> '+l.transformsTo.map(x=>D.leads[x]?.name||x).join(', '):''}</div>${S.leads[k]?btn('Travel / investigate',`routeTo('${l.node}')`,'good'):''}</div>`).join('');app.innerHTML=header()+`<div class="panel"><h2>Case Board</h2>${objectiveCard()}<h3>Next</h3>${nextStep()}<h3>Greyhook Status</h3>${greyhookStatus()}<h3>Routes</h3>${leads}<h3>Clues</h3>${S.clues.map(c=>`<div class="card"><div class="cx">${c}</div></div>`).join('')}</div>`}
function objectiveCard(){let title=S.greyhook?V.chapters.greyhook_fortress.title:V.chapters.sealed_ledger.title;let obj=S.greyhook?V.chapters.greyhook_fortress.objective:V.chapters.sealed_ledger.objective;return `<div class="card"><div class="ct">${title}</div><div class="cx">${obj}</div>${!S.contract&&!S.greyhook?btn('Accept The Sealed Ledger','acceptLedger()','pri'):''}${S.ledger?resolutionButtons():''}${S.prisonerOutcome&&!S.aftermath?btn('Resolve Greyhook chapter','resolveGreyhook()','pri'):''}</div>`}
function greyhookStatus(){return `<div class="card"><div class="ct">Alert ${S.greyhookAlert}/5 — ${greyhookAlertBand()}</div><div class="cx">Route: ${S.greyhookRoute||'none'}<br>Inside: ${S.greyhookInside?'yes':'no'}<br>Prisoner: ${S.prisonerContact?'contacted':'not contacted'}<br>Choice: ${S.prisonerChoice||'none'}<br>Outcome: ${S.prisonerOutcome||'unresolved'}<br>Aftermath: ${S.aftermath||'none'}</div></div>`}
function nextStep(){if(!S.contract&&!S.greyhook)return btn('Accept the Ledger case','acceptLedger()','pri');if(S.contract&&!S.ledger)return S.solutions.length?btn('Go to Old Watchtower','routeTo("tower")','good'):'Investigate a Ledger route marked on the map.';if(S.greyhook&&!S.greyhookInside)return 'Find a Greyhook approach, then commit at the gate.';if(S.greyhookInside&&!S.prisonerContact)return 'Reach the lower cells and make first contact with the sealed prisoner.';if(S.prisonerContact&&!S.prisonerOutcome)return 'Decide the prisoner fate: question, extract, silence, or trade.';if(S.prisonerOutcome&&!S.aftermath)return btn('Resolve Greyhook chapter','resolveGreyhook()','pri');return 'Next hook: '+V.chapters.greyhook_fortress.nextHook+'.'}
function routeTo(id){if(id==S.node)go('node');else if(n(S.node).exits.includes(id))travel(id);else{log('Route target: '+n(id).name+'. Use map roads to reach it.');go('map')}} window.routeTo=routeTo;

function acceptLedger(){S.contract=true;log('Accepted The Sealed Ledger.');go('board')} window.acceptLedger=acceptLedger;
function investigate(k){let L=lead(k),ok=S.stats[L.stat]>=L.dc-1;if(ok){S.leads[k]='viable';addSol(L.solution);addItem(L.item);addClue('Viable route: '+L.name);log(L.name+' becomes viable.')}else{S.leads[k]='failed_forward';addClue('Failed forward: '+L.name+' — '+L.softFail);(L.transformsTo||[]).forEach(t=>S.leads[t]='rumored');if(k=='greyhook_transfer')enterGreyhook('captured');log(L.name+' failed forward and opened another lead.')}render()} window.investigate=investigate;
function rumor(){let k=Object.keys(D.leads).find(x=>!S.leads[x]);if(k){S.leads[k]='rumored';log('Rumor gained: '+lead(k).name)}else log('No fresh rumor.');render()} window.rumor=rumor;
function ledgerWin(){S.ledger=true;addClue('Recovered the sealed ledger.');log('The ledger is yours.');go('board')} window.ledgerWin=ledgerWin;
function resolutionButtons(){return ['iron','rook','synod','hearth','red'].map(f=>btn('Resolve with '+D.factions[f].name,`finishLedger('${f}')`)).join('')}
function finishLedger(f){S.fac[f]+=10;S.contract=false;S.ledger=false;S.greyhook=true;['greyhook_supply','greyhook_quartermaster','greyhook_infirmary','greyhook_transfer'].forEach(k=>S.leads[k]='rumored');addClue('Greyhook Fortress holds a sealed prisoner.');setFlag('greyhook_unlocked');log('Ledger resolved. Greyhook chapter opens.');go('board')} window.finishLedger=finishLedger;

function greyhookApproaches(){let out='';for(const [id,a] of Object.entries(V.approaches.greyhook)){if(id=='escape')continue;let ok=!a.requiresAnySolution?.length||a.requiresAnySolution.some(x=>S.solutions.includes(x));if(ok)out+=btn(a.label,`enterGreyhook('${id}')`,id=='captured'?'bad':'pri')}return out}
function enterGreyhook(kind){let a=V.approaches.greyhook[kind];S.greyhook=true;S.greyhookInside=true;S.greyhookRoute=kind;S.node=a.entryNode;raiseAlert(a.alert||0,a.label);if(kind=='forgery')maybeEnemy('forgery');if(kind=='blackmail')maybeEnemy('blackmail');addClue('Greyhook entered: '+a.label+'. '+a.text);log('Entered Greyhook by '+a.label+'.');go('node')} window.enterGreyhook=enterGreyhook;
function scene(id){let sc=V.scenes[id];if(!sc)return;if(sc.requiresAnySolution&&!sc.requiresAnySolution.some(x=>S.solutions.includes(x))){raiseAlert(1,'scene requirement missing: '+id);log('The scene resists you and alert rises.');render();return}if(sc.requiresAnyItem&&!sc.requiresAnyItem.some(x=>S.items.includes(x))){raiseAlert(1,'missing key/paper for '+id);log('You lack the right key, paper, or cover.');render();return}if(sc.item)addItem(sc.item);if(sc.clue)addClue(sc.clue);if(id=='lower_cell_access')S.node='sealed_prisoner_cell';if(id=='archive_hook')setFlag('dead_name_index_hook');log(sc.clue||('Scene resolved: '+id));render()} window.scene=scene;

function prisonerContact(){S.prisonerContact=true;addClue('The prisoner whispers: The Crown of Ash was a right to name the dead.');maybeEnemy('prisoner_contact');log('The sealed prisoner answers once.');render()} window.prisonerContact=prisonerContact;
function prisonerChoice(c){if(!S.prisonerContact){log('Contact the prisoner first.');render();return}let ch=V.prisonerChoices[c];S.prisonerChoice=c;S.prisonerOutcome=ch.outcome;addItem(ch.item);deltaFac(ch.factionDeltas);S.morale=(S.morale||0)+(ch.morale||0);if(ch.crime&&!S.crimes.includes(ch.crime))S.crimes.push(ch.crime);raiseAlert(ch.alert||0,ch.label+' prisoner');companionReaction(c);addClue('Prisoner fate: '+ch.outcome+'. '+ch.nextHook);if(c=='extract')maybeEnemy('extract');log('Prisoner choice: '+ch.label+'.');render()} window.prisonerChoice=prisonerChoice;
function resolveGreyhook(){if(!S.prisonerOutcome){log('Choose prisoner fate first.');return render()}S.aftermath=`Greyhook resolved: ${S.prisonerOutcome}. Next: ${V.chapters.greyhook_fortress.nextHook}`;addClue(S.aftermath);setFlag('greyhook_resolved');S.greyhookInside=false;S.node=S.greyhookAlert>=5?'grey_road':'synod_archive';log(S.aftermath);render()} window.resolveGreyhook=resolveGreyhook;
function companionAngle(){let p=S.party[0];if(!p){log('No companion angle.');render();return}let name=comp(p).name;addClue(name+' creates a Greyhook angle.');if(p=='mara'||p=='nell'){addSol('greyhook_escape');raiseAlert(-1,name+' scouts an exit')}if(p=='hadrik')addSol('greyhook_supply_route');if(p=='ilyra')addSol('infirmary_route');if(p=='sarn'){S.leads.greyhook_escape_route='rumored';addClue('Sarn identifies the ink used on lower-cell records.')}if(p=='brig'){addSol('violent_distraction');raiseAlert(1,'Brig creates a violent distraction')}if(p=='miren'){S.fac.veil+=2;addClue('Miren hears dead names under the lower cells.')}log(name+' changes the Greyhook problem.');render()} window.companionAngle=companionAngle;
function enemyScene(){maybeEnemy(S.greyhookRoute||'lockdown');render()} window.enemyScene=enemyScene;
function patrol(){if(S.stats.presence>=7||S.items.includes('greyhook_search_stamp')){raiseAlert(-1,'patrol talked down');addClue('Patrol confrontation survived.')}else{raiseAlert(1,'patrol confrontation failed');S.crimes.push('Greyhook patrol beating');}render()} window.patrol=patrol;
function escapeMark(){addItem('greyhook_escape_mark');addSol('greyhook_escape');addClue('Escape mark found near the drainage stair.');log('Escape route secured.');render()} window.escapeMark=escapeMark;
function escapeOrCapture(){if(S.solutions.includes('greyhook_escape')||S.party.includes('mara')||S.party.includes('nell')){S.node='grey_road';S.greyhookInside=false;raiseAlert(-2,'forced escape succeeded');log('Forced escape succeeds.')}else{S.node='lower_cells';S.greyhookInside=true;S.crimes.push('captured in Greyhook');addClue('Escape failed forward into the captured-inside route.');log('Escape fails forward into capture.')}render()} window.escapeOrCapture=escapeOrCapture;

function company(){app.innerHTML=header()+`<div class="panel"><h2>Company</h2>${S.party.map(id=>{let c=comp(id);return `<div class="card"><div class="ct">${c.name} — ${c.role}</div><div class="cx">${c.text}<br><b>${c.ability}:</b> ${c.effect}</div></div>`}).join('')}<h3>Morale</h3>${tag(S.morale||0,'green')}<h3>Companion Reactions</h3>${S.reactions.length?S.reactions.map(r=>`<div class="card"><div class="cx">${r}</div></div>`).join(''):'<p>No major reaction yet.</p>'}<h3>Crimes</h3>${S.crimes.map(c=>tag(c,'red')).join('')||'<p>No recorded crimes.</p>'}</div>`}
function pack(){app.innerHTML=header()+`<div class="panel"><h2>Pack & Papers</h2>${S.items.map(id=>{let i=item(id);return `<div class="card"><div class="ct">${i.name} — ${i.type}</div><div class="cx">${i.text}<br>${(i.tags||[]).map(x=>tag(x)).join('')}</div></div>`}).join('')||'<p>No special items yet.</p>'}</div>`}
function camp(){app.innerHTML=header()+`<div class="panel"><h2>Camp</h2>${btn('Scout a rumor','rumor()')}${btn('Plan Greyhook escape / reduce alert','campEscape()')}${btn('Debrief prisoner choice','campDebrief()')}${btn('Rest and eat','rest()')}</div>`}
function campEscape(){if(S.greyhook){raiseAlert(-1,'camp escape planning');S.leads.greyhook_escape_route='rumored';addClue('Camp plan: Greyhook escape route considered.')}render()} window.campEscape=campEscape;
function campDebrief(){if(S.prisonerChoice){companionReaction(S.prisonerChoice);addClue('Camp debrief: prisoner fate discussed.')}else log('No prisoner choice to debrief yet.');render()} window.campDebrief=campDebrief;
function rest(){S.res.food=Math.max(0,S.res.food-1);S.res.day++;log('Rested.');render()} window.rest=rest;

render();